// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             v7.36.0--rc1
// source: inject/v1/inject.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationInjectServiceGetInjectContent = "/inject.v1.InjectService/GetInjectContent"
const OperationInjectServiceGetInjectTask = "/inject.v1.InjectService/GetInjectTask"
const OperationInjectServiceListInjectContents = "/inject.v1.InjectService/ListInjectContents"
const OperationInjectServiceListInjectLogs = "/inject.v1.InjectService/ListInjectLogs"
const OperationInjectServiceListInjectTasks = "/inject.v1.InjectService/ListInjectTasks"
const OperationInjectServiceRetryInjectContent = "/inject.v1.InjectService/RetryInjectContent"

type InjectServiceHTTPServer interface {
	GetInjectContent(context.Context, *GetInjectContentRequest) (*InjectContent, error)
	GetInjectTask(context.Context, *GetInjectTaskRequest) (*InjectTask, error)
	ListInjectContents(context.Context, *ListInjectContentsRequest) (*InjectContentSet, error)
	ListInjectLogs(context.Context, *ListInjectLogsRequest) (*InjectLogSet, error)
	ListInjectTasks(context.Context, *ListInjectTasksRequest) (*InjectTaskSet, error)
	RetryInjectContent(context.Context, *RetryInjectContentRequest) (*InjectContent, error)
}

func RegisterInjectServiceHTTPServer(s *http.Server, srv InjectServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/inject-contents", _InjectService_ListInjectContents0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/inject-contents/{id}", _InjectService_GetInjectContent0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/inject-contents/{id}/retry", _InjectService_RetryInjectContent0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/inject-tasks", _InjectService_ListInjectTasks0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/inject-tasks/{id}", _InjectService_GetInjectTask0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/inject-logs", _InjectService_ListInjectLogs0_HTTP_Handler(srv))
}

func _InjectService_ListInjectContents0_HTTP_Handler(srv InjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListInjectContentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInjectServiceListInjectContents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListInjectContents(ctx, req.(*ListInjectContentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InjectContentSet)
		return ctx.Result(200, reply)
	}
}

func _InjectService_GetInjectContent0_HTTP_Handler(srv InjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetInjectContentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInjectServiceGetInjectContent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInjectContent(ctx, req.(*GetInjectContentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InjectContent)
		return ctx.Result(200, reply)
	}
}

func _InjectService_RetryInjectContent0_HTTP_Handler(srv InjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RetryInjectContentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInjectServiceRetryInjectContent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RetryInjectContent(ctx, req.(*RetryInjectContentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InjectContent)
		return ctx.Result(200, reply)
	}
}

func _InjectService_ListInjectTasks0_HTTP_Handler(srv InjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListInjectTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInjectServiceListInjectTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListInjectTasks(ctx, req.(*ListInjectTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InjectTaskSet)
		return ctx.Result(200, reply)
	}
}

func _InjectService_GetInjectTask0_HTTP_Handler(srv InjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetInjectTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInjectServiceGetInjectTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInjectTask(ctx, req.(*GetInjectTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InjectTask)
		return ctx.Result(200, reply)
	}
}

func _InjectService_ListInjectLogs0_HTTP_Handler(srv InjectServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListInjectLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInjectServiceListInjectLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListInjectLogs(ctx, req.(*ListInjectLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*InjectLogSet)
		return ctx.Result(200, reply)
	}
}

type InjectServiceHTTPClient interface {
	GetInjectContent(ctx context.Context, req *GetInjectContentRequest, opts ...http.CallOption) (rsp *InjectContent, err error)
	GetInjectTask(ctx context.Context, req *GetInjectTaskRequest, opts ...http.CallOption) (rsp *InjectTask, err error)
	ListInjectContents(ctx context.Context, req *ListInjectContentsRequest, opts ...http.CallOption) (rsp *InjectContentSet, err error)
	ListInjectLogs(ctx context.Context, req *ListInjectLogsRequest, opts ...http.CallOption) (rsp *InjectLogSet, err error)
	ListInjectTasks(ctx context.Context, req *ListInjectTasksRequest, opts ...http.CallOption) (rsp *InjectTaskSet, err error)
	RetryInjectContent(ctx context.Context, req *RetryInjectContentRequest, opts ...http.CallOption) (rsp *InjectContent, err error)
}

type InjectServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewInjectServiceHTTPClient(client *http.Client) InjectServiceHTTPClient {
	return &InjectServiceHTTPClientImpl{client}
}

func (c *InjectServiceHTTPClientImpl) GetInjectContent(ctx context.Context, in *GetInjectContentRequest, opts ...http.CallOption) (*InjectContent, error) {
	var out InjectContent
	pattern := "/v1/inject-contents/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationInjectServiceGetInjectContent),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InjectServiceHTTPClientImpl) GetInjectTask(ctx context.Context, in *GetInjectTaskRequest, opts ...http.CallOption) (*InjectTask, error) {
	var out InjectTask
	pattern := "/v1/inject-tasks/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationInjectServiceGetInjectTask),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InjectServiceHTTPClientImpl) ListInjectContents(ctx context.Context, in *ListInjectContentsRequest, opts ...http.CallOption) (*InjectContentSet, error) {
	var out InjectContentSet
	pattern := "/v1/inject-contents"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationInjectServiceListInjectContents),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InjectServiceHTTPClientImpl) ListInjectLogs(ctx context.Context, in *ListInjectLogsRequest, opts ...http.CallOption) (*InjectLogSet, error) {
	var out InjectLogSet
	pattern := "/v1/inject-logs"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationInjectServiceListInjectLogs),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InjectServiceHTTPClientImpl) ListInjectTasks(ctx context.Context, in *ListInjectTasksRequest, opts ...http.CallOption) (*InjectTaskSet, error) {
	var out InjectTaskSet
	pattern := "/v1/inject-tasks"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationInjectServiceListInjectTasks),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *InjectServiceHTTPClientImpl) RetryInjectContent(ctx context.Context, in *RetryInjectContentRequest, opts ...http.CallOption) (*InjectContent, error) {
	var out InjectContent
	pattern := "/v1/inject-contents/{id}/retry"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationInjectServiceRetryInjectContent),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
