// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: inject/v1/inject.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InjectContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceType  uint32                 `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    int64                  `protobuf:"varint,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,4,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	EpisodeId     int64                  `protobuf:"varint,5,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	MediaId       int64                  `protobuf:"varint,6,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Action        uint32                 `protobuf:"varint,7,opt,name=action,proto3" json:"action,omitempty"`
	LastTaskId    int64                  `protobuf:"varint,8,opt,name=last_task_id,json=lastTaskId,proto3" json:"last_task_id,omitempty"`
	Status        uint32                 `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	FailReason    string                 `protobuf:"bytes,10,opt,name=fail_reason,json=failReason,proto3" json:"fail_reason,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectContent) Reset() {
	*x = InjectContent{}
	mi := &file_inject_v1_inject_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectContent) ProtoMessage() {}

func (x *InjectContent) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectContent.ProtoReflect.Descriptor instead.
func (*InjectContent) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{0}
}

func (x *InjectContent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InjectContent) GetResourceType() uint32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *InjectContent) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *InjectContent) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *InjectContent) GetEpisodeId() int64 {
	if x != nil {
		return x.EpisodeId
	}
	return 0
}

func (x *InjectContent) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *InjectContent) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *InjectContent) GetLastTaskId() int64 {
	if x != nil {
		return x.LastTaskId
	}
	return 0
}

func (x *InjectContent) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InjectContent) GetFailReason() string {
	if x != nil {
		return x.FailReason
	}
	return ""
}

func (x *InjectContent) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *InjectContent) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type InjectContentSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contents      []*InjectContent       `protobuf:"bytes,1,rep,name=contents,proto3" json:"contents,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectContentSet) Reset() {
	*x = InjectContentSet{}
	mi := &file_inject_v1_inject_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectContentSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectContentSet) ProtoMessage() {}

func (x *InjectContentSet) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectContentSet.ProtoReflect.Descriptor instead.
func (*InjectContentSet) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{1}
}

func (x *InjectContentSet) GetContents() []*InjectContent {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *InjectContentSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListInjectContentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInjectContentsRequest) Reset() {
	*x = ListInjectContentsRequest{}
	mi := &file_inject_v1_inject_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInjectContentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInjectContentsRequest) ProtoMessage() {}

func (x *ListInjectContentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInjectContentsRequest.ProtoReflect.Descriptor instead.
func (*ListInjectContentsRequest) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{2}
}

func (x *ListInjectContentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInjectContentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetInjectContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInjectContentRequest) Reset() {
	*x = GetInjectContentRequest{}
	mi := &file_inject_v1_inject_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInjectContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInjectContentRequest) ProtoMessage() {}

func (x *GetInjectContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInjectContentRequest.ProtoReflect.Descriptor instead.
func (*GetInjectContentRequest) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{3}
}

func (x *GetInjectContentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RetryInjectContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryInjectContentRequest) Reset() {
	*x = RetryInjectContentRequest{}
	mi := &file_inject_v1_inject_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryInjectContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryInjectContentRequest) ProtoMessage() {}

func (x *RetryInjectContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryInjectContentRequest.ProtoReflect.Descriptor instead.
func (*RetryInjectContentRequest) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{4}
}

func (x *RetryInjectContentRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type InjectTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentId     int64                  `protobuf:"varint,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	ResourceType  uint32                 `protobuf:"varint,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    int64                  `protobuf:"varint,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,5,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	EpisodeId     int64                  `protobuf:"varint,6,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	MediaId       int64                  `protobuf:"varint,7,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Action        uint32                 `protobuf:"varint,8,opt,name=action,proto3" json:"action,omitempty"`
	Status        uint32                 `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectTask) Reset() {
	*x = InjectTask{}
	mi := &file_inject_v1_inject_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectTask) ProtoMessage() {}

func (x *InjectTask) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectTask.ProtoReflect.Descriptor instead.
func (*InjectTask) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{5}
}

func (x *InjectTask) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InjectTask) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *InjectTask) GetResourceType() uint32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *InjectTask) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *InjectTask) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *InjectTask) GetEpisodeId() int64 {
	if x != nil {
		return x.EpisodeId
	}
	return 0
}

func (x *InjectTask) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *InjectTask) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *InjectTask) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InjectTask) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *InjectTask) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type InjectTaskSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*InjectTask          `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectTaskSet) Reset() {
	*x = InjectTaskSet{}
	mi := &file_inject_v1_inject_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectTaskSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectTaskSet) ProtoMessage() {}

func (x *InjectTaskSet) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectTaskSet.ProtoReflect.Descriptor instead.
func (*InjectTaskSet) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{6}
}

func (x *InjectTaskSet) GetTasks() []*InjectTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *InjectTaskSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListInjectTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInjectTasksRequest) Reset() {
	*x = ListInjectTasksRequest{}
	mi := &file_inject_v1_inject_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInjectTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInjectTasksRequest) ProtoMessage() {}

func (x *ListInjectTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInjectTasksRequest.ProtoReflect.Descriptor instead.
func (*ListInjectTasksRequest) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{7}
}

func (x *ListInjectTasksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInjectTasksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetInjectTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInjectTaskRequest) Reset() {
	*x = GetInjectTaskRequest{}
	mi := &file_inject_v1_inject_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInjectTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInjectTaskRequest) ProtoMessage() {}

func (x *GetInjectTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInjectTaskRequest.ProtoReflect.Descriptor instead.
func (*GetInjectTaskRequest) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{8}
}

func (x *GetInjectTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type InjectLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ContentId     int64                  `protobuf:"varint,3,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	SpId          int64                  `protobuf:"varint,4,opt,name=sp_id,json=spId,proto3" json:"sp_id,omitempty"`
	ResourceType  uint32                 `protobuf:"varint,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId    int64                  `protobuf:"varint,6,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	VideoId       int64                  `protobuf:"varint,7,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	EpisodeId     int64                  `protobuf:"varint,8,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	MediaId       int64                  `protobuf:"varint,9,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Action        uint32                 `protobuf:"varint,10,opt,name=action,proto3" json:"action,omitempty"`
	CorrelateId   string                 `protobuf:"bytes,11,opt,name=correlate_id,json=correlateId,proto3" json:"correlate_id,omitempty"`
	SyncStatus    uint32                 `protobuf:"varint,12,opt,name=sync_status,json=syncStatus,proto3" json:"sync_status,omitempty"`
	AsyncStatus   uint32                 `protobuf:"varint,13,opt,name=async_status,json=asyncStatus,proto3" json:"async_status,omitempty"`
	SyncMessage   string                 `protobuf:"bytes,14,opt,name=sync_message,json=syncMessage,proto3" json:"sync_message,omitempty"`
	AsyncMessage  string                 `protobuf:"bytes,15,opt,name=async_message,json=asyncMessage,proto3" json:"async_message,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectLog) Reset() {
	*x = InjectLog{}
	mi := &file_inject_v1_inject_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectLog) ProtoMessage() {}

func (x *InjectLog) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectLog.ProtoReflect.Descriptor instead.
func (*InjectLog) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{9}
}

func (x *InjectLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InjectLog) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *InjectLog) GetContentId() int64 {
	if x != nil {
		return x.ContentId
	}
	return 0
}

func (x *InjectLog) GetSpId() int64 {
	if x != nil {
		return x.SpId
	}
	return 0
}

func (x *InjectLog) GetResourceType() uint32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *InjectLog) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *InjectLog) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *InjectLog) GetEpisodeId() int64 {
	if x != nil {
		return x.EpisodeId
	}
	return 0
}

func (x *InjectLog) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *InjectLog) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *InjectLog) GetCorrelateId() string {
	if x != nil {
		return x.CorrelateId
	}
	return ""
}

func (x *InjectLog) GetSyncStatus() uint32 {
	if x != nil {
		return x.SyncStatus
	}
	return 0
}

func (x *InjectLog) GetAsyncStatus() uint32 {
	if x != nil {
		return x.AsyncStatus
	}
	return 0
}

func (x *InjectLog) GetSyncMessage() string {
	if x != nil {
		return x.SyncMessage
	}
	return ""
}

func (x *InjectLog) GetAsyncMessage() string {
	if x != nil {
		return x.AsyncMessage
	}
	return ""
}

func (x *InjectLog) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *InjectLog) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type InjectLogSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*InjectLog           `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectLogSet) Reset() {
	*x = InjectLogSet{}
	mi := &file_inject_v1_inject_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectLogSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectLogSet) ProtoMessage() {}

func (x *InjectLogSet) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectLogSet.ProtoReflect.Descriptor instead.
func (*InjectLogSet) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{10}
}

func (x *InjectLogSet) GetLogs() []*InjectLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *InjectLogSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListInjectLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInjectLogsRequest) Reset() {
	*x = ListInjectLogsRequest{}
	mi := &file_inject_v1_inject_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInjectLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInjectLogsRequest) ProtoMessage() {}

func (x *ListInjectLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inject_v1_inject_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInjectLogsRequest.ProtoReflect.Descriptor instead.
func (*ListInjectLogsRequest) Descriptor() ([]byte, []int) {
	return file_inject_v1_inject_proto_rawDescGZIP(), []int{11}
}

func (x *ListInjectLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInjectLogsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

var File_inject_v1_inject_proto protoreflect.FileDescriptor

const file_inject_v1_inject_proto_rawDesc = "" +
	"\n" +
	"\x16inject/v1/inject.proto\x12\tinject.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x03\n" +
	"\rInjectContent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rresource_type\x18\x02 \x01(\rR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\x03R\n" +
	"resourceId\x12\x19\n" +
	"\bvideo_id\x18\x04 \x01(\x03R\avideoId\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x05 \x01(\x03R\tepisodeId\x12\x19\n" +
	"\bmedia_id\x18\x06 \x01(\x03R\amediaId\x12\x16\n" +
	"\x06action\x18\a \x01(\rR\x06action\x12 \n" +
	"\flast_task_id\x18\b \x01(\x03R\n" +
	"lastTaskId\x12\x16\n" +
	"\x06status\x18\t \x01(\rR\x06status\x12\x1f\n" +
	"\vfail_reason\x18\n" +
	" \x01(\tR\n" +
	"failReason\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"p\n" +
	"\x10InjectContentSet\x124\n" +
	"\bcontents\x18\x01 \x03(\v2\x18.inject.v1.InjectContentR\bcontents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"W\n" +
	"\x19ListInjectContentsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"/\n" +
	"\x17GetInjectContentRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\x03B\x04\xe2A\x01\x02R\x02id\"1\n" +
	"\x19RetryInjectContentRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\x03B\x04\xe2A\x01\x02R\x02id\"\x80\x03\n" +
	"\n" +
	"InjectTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\x03R\tcontentId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\rR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\x03R\n" +
	"resourceId\x12\x19\n" +
	"\bvideo_id\x18\x05 \x01(\x03R\avideoId\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x06 \x01(\x03R\tepisodeId\x12\x19\n" +
	"\bmedia_id\x18\a \x01(\x03R\amediaId\x12\x16\n" +
	"\x06action\x18\b \x01(\rR\x06action\x12\x16\n" +
	"\x06status\x18\t \x01(\rR\x06status\x12;\n" +
	"\vcreate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"d\n" +
	"\rInjectTaskSet\x12+\n" +
	"\x05tasks\x18\x01 \x03(\v2\x15.inject.v1.InjectTaskR\x05tasks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"T\n" +
	"\x16ListInjectTasksRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\",\n" +
	"\x14GetInjectTaskRequest\x12\x14\n" +
	"\x02id\x18\x01 \x01(\x03B\x04\xe2A\x01\x02R\x02id\"\xc4\x04\n" +
	"\tInjectLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x03 \x01(\x03R\tcontentId\x12\x13\n" +
	"\x05sp_id\x18\x04 \x01(\x03R\x04spId\x12#\n" +
	"\rresource_type\x18\x05 \x01(\rR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x06 \x01(\x03R\n" +
	"resourceId\x12\x19\n" +
	"\bvideo_id\x18\a \x01(\x03R\avideoId\x12\x1d\n" +
	"\n" +
	"episode_id\x18\b \x01(\x03R\tepisodeId\x12\x19\n" +
	"\bmedia_id\x18\t \x01(\x03R\amediaId\x12\x16\n" +
	"\x06action\x18\n" +
	" \x01(\rR\x06action\x12!\n" +
	"\fcorrelate_id\x18\v \x01(\tR\vcorrelateId\x12\x1f\n" +
	"\vsync_status\x18\f \x01(\rR\n" +
	"syncStatus\x12!\n" +
	"\fasync_status\x18\r \x01(\rR\vasyncStatus\x12!\n" +
	"\fsync_message\x18\x0e \x01(\tR\vsyncMessage\x12#\n" +
	"\rasync_message\x18\x0f \x01(\tR\fasyncMessage\x12;\n" +
	"\vcreate_time\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"`\n" +
	"\fInjectLogSet\x12(\n" +
	"\x04logs\x18\x01 \x03(\v2\x14.inject.v1.InjectLogR\x04logs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"S\n" +
	"\x15ListInjectLogsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken2\xaf\x05\n" +
	"\rInjectService\x12t\n" +
	"\x12ListInjectContents\x12$.inject.v1.ListInjectContentsRequest\x1a\x1b.inject.v1.InjectContentSet\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/inject-contents\x12r\n" +
	"\x10GetInjectContent\x12\".inject.v1.GetInjectContentRequest\x1a\x18.inject.v1.InjectContent\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/inject-contents/{id}\x12|\n" +
	"\x12RetryInjectContent\x12$.inject.v1.RetryInjectContentRequest\x1a\x18.inject.v1.InjectContent\"&\x82\xd3\xe4\x93\x02 \"\x1e/v1/inject-contents/{id}/retry\x12h\n" +
	"\x0fListInjectTasks\x12!.inject.v1.ListInjectTasksRequest\x1a\x18.inject.v1.InjectTaskSet\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/inject-tasks\x12f\n" +
	"\rGetInjectTask\x12\x1f.inject.v1.GetInjectTaskRequest\x1a\x15.inject.v1.InjectTask\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/inject-tasks/{id}\x12d\n" +
	"\x0eListInjectLogs\x12 .inject.v1.ListInjectLogsRequest\x1a\x17.inject.v1.InjectLogSet\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/inject-logsB\x17Z\x15crow/api/inject/v1;v1b\x06proto3"

var (
	file_inject_v1_inject_proto_rawDescOnce sync.Once
	file_inject_v1_inject_proto_rawDescData []byte
)

func file_inject_v1_inject_proto_rawDescGZIP() []byte {
	file_inject_v1_inject_proto_rawDescOnce.Do(func() {
		file_inject_v1_inject_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inject_v1_inject_proto_rawDesc), len(file_inject_v1_inject_proto_rawDesc)))
	})
	return file_inject_v1_inject_proto_rawDescData
}

var file_inject_v1_inject_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_inject_v1_inject_proto_goTypes = []any{
	(*InjectContent)(nil),             // 0: inject.v1.InjectContent
	(*InjectContentSet)(nil),          // 1: inject.v1.InjectContentSet
	(*ListInjectContentsRequest)(nil), // 2: inject.v1.ListInjectContentsRequest
	(*GetInjectContentRequest)(nil),   // 3: inject.v1.GetInjectContentRequest
	(*RetryInjectContentRequest)(nil), // 4: inject.v1.RetryInjectContentRequest
	(*InjectTask)(nil),                // 5: inject.v1.InjectTask
	(*InjectTaskSet)(nil),             // 6: inject.v1.InjectTaskSet
	(*ListInjectTasksRequest)(nil),    // 7: inject.v1.ListInjectTasksRequest
	(*GetInjectTaskRequest)(nil),      // 8: inject.v1.GetInjectTaskRequest
	(*InjectLog)(nil),                 // 9: inject.v1.InjectLog
	(*InjectLogSet)(nil),              // 10: inject.v1.InjectLogSet
	(*ListInjectLogsRequest)(nil),     // 11: inject.v1.ListInjectLogsRequest
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_inject_v1_inject_proto_depIdxs = []int32{
	12, // 0: inject.v1.InjectContent.create_time:type_name -> google.protobuf.Timestamp
	12, // 1: inject.v1.InjectContent.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: inject.v1.InjectContentSet.contents:type_name -> inject.v1.InjectContent
	12, // 3: inject.v1.InjectTask.create_time:type_name -> google.protobuf.Timestamp
	12, // 4: inject.v1.InjectTask.update_time:type_name -> google.protobuf.Timestamp
	5,  // 5: inject.v1.InjectTaskSet.tasks:type_name -> inject.v1.InjectTask
	12, // 6: inject.v1.InjectLog.create_time:type_name -> google.protobuf.Timestamp
	12, // 7: inject.v1.InjectLog.update_time:type_name -> google.protobuf.Timestamp
	9,  // 8: inject.v1.InjectLogSet.logs:type_name -> inject.v1.InjectLog
	2,  // 9: inject.v1.InjectService.ListInjectContents:input_type -> inject.v1.ListInjectContentsRequest
	3,  // 10: inject.v1.InjectService.GetInjectContent:input_type -> inject.v1.GetInjectContentRequest
	4,  // 11: inject.v1.InjectService.RetryInjectContent:input_type -> inject.v1.RetryInjectContentRequest
	7,  // 12: inject.v1.InjectService.ListInjectTasks:input_type -> inject.v1.ListInjectTasksRequest
	8,  // 13: inject.v1.InjectService.GetInjectTask:input_type -> inject.v1.GetInjectTaskRequest
	11, // 14: inject.v1.InjectService.ListInjectLogs:input_type -> inject.v1.ListInjectLogsRequest
	1,  // 15: inject.v1.InjectService.ListInjectContents:output_type -> inject.v1.InjectContentSet
	0,  // 16: inject.v1.InjectService.GetInjectContent:output_type -> inject.v1.InjectContent
	0,  // 17: inject.v1.InjectService.RetryInjectContent:output_type -> inject.v1.InjectContent
	6,  // 18: inject.v1.InjectService.ListInjectTasks:output_type -> inject.v1.InjectTaskSet
	5,  // 19: inject.v1.InjectService.GetInjectTask:output_type -> inject.v1.InjectTask
	10, // 20: inject.v1.InjectService.ListInjectLogs:output_type -> inject.v1.InjectLogSet
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_inject_v1_inject_proto_init() }
func file_inject_v1_inject_proto_init() {
	if File_inject_v1_inject_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inject_v1_inject_proto_rawDesc), len(file_inject_v1_inject_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inject_v1_inject_proto_goTypes,
		DependencyIndexes: file_inject_v1_inject_proto_depIdxs,
		MessageInfos:      file_inject_v1_inject_proto_msgTypes,
	}.Build()
	File_inject_v1_inject_proto = out.File
	file_inject_v1_inject_proto_goTypes = nil
	file_inject_v1_inject_proto_depIdxs = nil
}
