// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc1
// source: inject/v1/inject.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InjectService_ListInjectContents_FullMethodName = "/inject.v1.InjectService/ListInjectContents"
	InjectService_GetInjectContent_FullMethodName   = "/inject.v1.InjectService/GetInjectContent"
	InjectService_RetryInjectContent_FullMethodName = "/inject.v1.InjectService/RetryInjectContent"
	InjectService_ListInjectTasks_FullMethodName    = "/inject.v1.InjectService/ListInjectTasks"
	InjectService_GetInjectTask_FullMethodName      = "/inject.v1.InjectService/GetInjectTask"
	InjectService_ListInjectLogs_FullMethodName     = "/inject.v1.InjectService/ListInjectLogs"
)

// InjectServiceClient is the client API for InjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InjectServiceClient interface {
	ListInjectContents(ctx context.Context, in *ListInjectContentsRequest, opts ...grpc.CallOption) (*InjectContentSet, error)
	GetInjectContent(ctx context.Context, in *GetInjectContentRequest, opts ...grpc.CallOption) (*InjectContent, error)
	RetryInjectContent(ctx context.Context, in *RetryInjectContentRequest, opts ...grpc.CallOption) (*InjectContent, error)
	ListInjectTasks(ctx context.Context, in *ListInjectTasksRequest, opts ...grpc.CallOption) (*InjectTaskSet, error)
	GetInjectTask(ctx context.Context, in *GetInjectTaskRequest, opts ...grpc.CallOption) (*InjectTask, error)
	ListInjectLogs(ctx context.Context, in *ListInjectLogsRequest, opts ...grpc.CallOption) (*InjectLogSet, error)
}

type injectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInjectServiceClient(cc grpc.ClientConnInterface) InjectServiceClient {
	return &injectServiceClient{cc}
}

func (c *injectServiceClient) ListInjectContents(ctx context.Context, in *ListInjectContentsRequest, opts ...grpc.CallOption) (*InjectContentSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectContentSet)
	err := c.cc.Invoke(ctx, InjectService_ListInjectContents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectServiceClient) GetInjectContent(ctx context.Context, in *GetInjectContentRequest, opts ...grpc.CallOption) (*InjectContent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectContent)
	err := c.cc.Invoke(ctx, InjectService_GetInjectContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectServiceClient) RetryInjectContent(ctx context.Context, in *RetryInjectContentRequest, opts ...grpc.CallOption) (*InjectContent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectContent)
	err := c.cc.Invoke(ctx, InjectService_RetryInjectContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectServiceClient) ListInjectTasks(ctx context.Context, in *ListInjectTasksRequest, opts ...grpc.CallOption) (*InjectTaskSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectTaskSet)
	err := c.cc.Invoke(ctx, InjectService_ListInjectTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectServiceClient) GetInjectTask(ctx context.Context, in *GetInjectTaskRequest, opts ...grpc.CallOption) (*InjectTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectTask)
	err := c.cc.Invoke(ctx, InjectService_GetInjectTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *injectServiceClient) ListInjectLogs(ctx context.Context, in *ListInjectLogsRequest, opts ...grpc.CallOption) (*InjectLogSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectLogSet)
	err := c.cc.Invoke(ctx, InjectService_ListInjectLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InjectServiceServer is the server API for InjectService service.
// All implementations must embed UnimplementedInjectServiceServer
// for forward compatibility.
type InjectServiceServer interface {
	ListInjectContents(context.Context, *ListInjectContentsRequest) (*InjectContentSet, error)
	GetInjectContent(context.Context, *GetInjectContentRequest) (*InjectContent, error)
	RetryInjectContent(context.Context, *RetryInjectContentRequest) (*InjectContent, error)
	ListInjectTasks(context.Context, *ListInjectTasksRequest) (*InjectTaskSet, error)
	GetInjectTask(context.Context, *GetInjectTaskRequest) (*InjectTask, error)
	ListInjectLogs(context.Context, *ListInjectLogsRequest) (*InjectLogSet, error)
	mustEmbedUnimplementedInjectServiceServer()
}

// UnimplementedInjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInjectServiceServer struct{}

func (UnimplementedInjectServiceServer) ListInjectContents(context.Context, *ListInjectContentsRequest) (*InjectContentSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInjectContents not implemented")
}
func (UnimplementedInjectServiceServer) GetInjectContent(context.Context, *GetInjectContentRequest) (*InjectContent, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInjectContent not implemented")
}
func (UnimplementedInjectServiceServer) RetryInjectContent(context.Context, *RetryInjectContentRequest) (*InjectContent, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryInjectContent not implemented")
}
func (UnimplementedInjectServiceServer) ListInjectTasks(context.Context, *ListInjectTasksRequest) (*InjectTaskSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInjectTasks not implemented")
}
func (UnimplementedInjectServiceServer) GetInjectTask(context.Context, *GetInjectTaskRequest) (*InjectTask, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInjectTask not implemented")
}
func (UnimplementedInjectServiceServer) ListInjectLogs(context.Context, *ListInjectLogsRequest) (*InjectLogSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInjectLogs not implemented")
}
func (UnimplementedInjectServiceServer) mustEmbedUnimplementedInjectServiceServer() {}
func (UnimplementedInjectServiceServer) testEmbeddedByValue()                       {}

// UnsafeInjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InjectServiceServer will
// result in compilation errors.
type UnsafeInjectServiceServer interface {
	mustEmbedUnimplementedInjectServiceServer()
}

func RegisterInjectServiceServer(s grpc.ServiceRegistrar, srv InjectServiceServer) {
	// If the following call panics, it indicates UnimplementedInjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InjectService_ServiceDesc, srv)
}

func _InjectService_ListInjectContents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInjectContentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectServiceServer).ListInjectContents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InjectService_ListInjectContents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectServiceServer).ListInjectContents(ctx, req.(*ListInjectContentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectService_GetInjectContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInjectContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectServiceServer).GetInjectContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InjectService_GetInjectContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectServiceServer).GetInjectContent(ctx, req.(*GetInjectContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectService_RetryInjectContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryInjectContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectServiceServer).RetryInjectContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InjectService_RetryInjectContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectServiceServer).RetryInjectContent(ctx, req.(*RetryInjectContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectService_ListInjectTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInjectTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectServiceServer).ListInjectTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InjectService_ListInjectTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectServiceServer).ListInjectTasks(ctx, req.(*ListInjectTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectService_GetInjectTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInjectTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectServiceServer).GetInjectTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InjectService_GetInjectTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectServiceServer).GetInjectTask(ctx, req.(*GetInjectTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InjectService_ListInjectLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInjectLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InjectServiceServer).ListInjectLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InjectService_ListInjectLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InjectServiceServer).ListInjectLogs(ctx, req.(*ListInjectLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InjectService_ServiceDesc is the grpc.ServiceDesc for InjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inject.v1.InjectService",
	HandlerType: (*InjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInjectContents",
			Handler:    _InjectService_ListInjectContents_Handler,
		},
		{
			MethodName: "GetInjectContent",
			Handler:    _InjectService_GetInjectContent_Handler,
		},
		{
			MethodName: "RetryInjectContent",
			Handler:    _InjectService_RetryInjectContent_Handler,
		},
		{
			MethodName: "ListInjectTasks",
			Handler:    _InjectService_ListInjectTasks_Handler,
		},
		{
			MethodName: "GetInjectTask",
			Handler:    _InjectService_GetInjectTask_Handler,
		},
		{
			MethodName: "ListInjectLogs",
			Handler:    _InjectService_ListInjectLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inject/v1/inject.proto",
}
