// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: admin/v1/admin.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationAdminServiceCreateAdmin = "/admin.v1.AdminService/CreateAdmin"
const OperationAdminServiceCreateAdminRole = "/admin.v1.AdminService/CreateAdminRole"
const OperationAdminServiceCreateGroupPermission = "/admin.v1.AdminService/CreateGroupPermission"
const OperationAdminServiceCreatePermission = "/admin.v1.AdminService/CreatePermission"
const OperationAdminServiceCreateRole = "/admin.v1.AdminService/CreateRole"
const OperationAdminServiceDeleteAdmin = "/admin.v1.AdminService/DeleteAdmin"
const OperationAdminServiceDeleteAdminRole = "/admin.v1.AdminService/DeleteAdminRole"
const OperationAdminServiceDeleteGroupPermission = "/admin.v1.AdminService/DeleteGroupPermission"
const OperationAdminServiceDeletePermission = "/admin.v1.AdminService/DeletePermission"
const OperationAdminServiceDeleteRole = "/admin.v1.AdminService/DeleteRole"
const OperationAdminServiceGetAdmin = "/admin.v1.AdminService/GetAdmin"
const OperationAdminServiceGetAdminRole = "/admin.v1.AdminService/GetAdminRole"
const OperationAdminServiceGetGroupPermission = "/admin.v1.AdminService/GetGroupPermission"
const OperationAdminServiceGetPermission = "/admin.v1.AdminService/GetPermission"
const OperationAdminServiceGetRole = "/admin.v1.AdminService/GetRole"
const OperationAdminServiceListAdminOperationLogs = "/admin.v1.AdminService/ListAdminOperationLogs"
const OperationAdminServiceListAdminRoles = "/admin.v1.AdminService/ListAdminRoles"
const OperationAdminServiceListAdmins = "/admin.v1.AdminService/ListAdmins"
const OperationAdminServiceListGroupPermissions = "/admin.v1.AdminService/ListGroupPermissions"
const OperationAdminServiceListPermissions = "/admin.v1.AdminService/ListPermissions"
const OperationAdminServiceListRoles = "/admin.v1.AdminService/ListRoles"
const OperationAdminServiceListSystemLogs = "/admin.v1.AdminService/ListSystemLogs"
const OperationAdminServiceUpdateAdmin = "/admin.v1.AdminService/UpdateAdmin"
const OperationAdminServiceUpdateAdminRole = "/admin.v1.AdminService/UpdateAdminRole"
const OperationAdminServiceUpdateGroupPermission = "/admin.v1.AdminService/UpdateGroupPermission"
const OperationAdminServiceUpdatePermission = "/admin.v1.AdminService/UpdatePermission"
const OperationAdminServiceUpdateRole = "/admin.v1.AdminService/UpdateRole"

type AdminServiceHTTPServer interface {
	CreateAdmin(context.Context, *CreateAdminRequest) (*Admin, error)
	CreateAdminRole(context.Context, *CreateAdminRoleRequest) (*AdminRole, error)
	CreateGroupPermission(context.Context, *CreateGroupPermissionRequest) (*GroupPermission, error)
	CreatePermission(context.Context, *CreatePermissionRequest) (*Permission, error)
	CreateRole(context.Context, *CreateRoleRequest) (*Role, error)
	DeleteAdmin(context.Context, *DeleteAdminRequest) (*emptypb.Empty, error)
	DeleteAdminRole(context.Context, *DeleteAdminRoleRequest) (*emptypb.Empty, error)
	DeleteGroupPermission(context.Context, *DeleteGroupPermissionRequest) (*emptypb.Empty, error)
	DeletePermission(context.Context, *DeletePermissionRequest) (*emptypb.Empty, error)
	DeleteRole(context.Context, *DeleteRoleRequest) (*emptypb.Empty, error)
	GetAdmin(context.Context, *GetAdminRequest) (*Admin, error)
	GetAdminRole(context.Context, *GetAdminRoleRequest) (*AdminRole, error)
	GetGroupPermission(context.Context, *GetGroupPermissionRequest) (*GroupPermission, error)
	GetPermission(context.Context, *GetPermissionRequest) (*Permission, error)
	GetRole(context.Context, *GetRoleRequest) (*Role, error)
	ListAdminOperationLogs(context.Context, *ListAdminOperationLogsRequest) (*AdminOperationLogSet, error)
	ListAdminRoles(context.Context, *ListAdminRolesRequest) (*AdminRoleSet, error)
	ListAdmins(context.Context, *ListAdminsRequest) (*AdminSet, error)
	ListGroupPermissions(context.Context, *ListGroupPermissionsRequest) (*GroupPermissionSet, error)
	ListPermissions(context.Context, *ListPermissionsRequest) (*PermissionSet, error)
	ListRoles(context.Context, *ListRolesRequest) (*RoleSet, error)
	ListSystemLogs(context.Context, *ListSystemLogsRequest) (*SystemLogSet, error)
	UpdateAdmin(context.Context, *UpdateAdminRequest) (*Admin, error)
	UpdateAdminRole(context.Context, *UpdateAdminRoleRequest) (*AdminRole, error)
	UpdateGroupPermission(context.Context, *UpdateGroupPermissionRequest) (*GroupPermission, error)
	UpdatePermission(context.Context, *UpdatePermissionRequest) (*Permission, error)
	UpdateRole(context.Context, *UpdateRoleRequest) (*Role, error)
}

func RegisterAdminServiceHTTPServer(s *http.Server, srv AdminServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/admins/create", _AdminService_CreateAdmin0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admins/{id}", _AdminService_GetAdmin0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admins", _AdminService_ListAdmins0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/admins/update", _AdminService_UpdateAdmin0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admins/{id}", _AdminService_DeleteAdmin0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/roles/create", _AdminService_CreateRole0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/roles/{id}", _AdminService_GetRole0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/roles", _AdminService_ListRoles0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/roles/update", _AdminService_UpdateRole0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/roles/{id}", _AdminService_DeleteRole0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/admin-roles/create", _AdminService_CreateAdminRole0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin-roles/{id}", _AdminService_GetAdminRole0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin-roles", _AdminService_ListAdminRoles0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/admin-roles/update", _AdminService_UpdateAdminRole0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/admin-roles/{id}", _AdminService_DeleteAdminRole0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/permissions/create", _AdminService_CreatePermission0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/permissions/{id}", _AdminService_GetPermission0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/permissions", _AdminService_ListPermissions0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/permissions/update", _AdminService_UpdatePermission0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/permissions/{id}", _AdminService_DeletePermission0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/group-permissions/create", _AdminService_CreateGroupPermission0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/group-permissions/{id}", _AdminService_GetGroupPermission0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/group-permissions", _AdminService_ListGroupPermissions0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/group-permissions/update", _AdminService_UpdateGroupPermission0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/group-permissions/{id}", _AdminService_DeleteGroupPermission0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/admin-operation-logs", _AdminService_ListAdminOperationLogs0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/system-logs", _AdminService_ListSystemLogs0_HTTP_Handler(srv))
}

func _AdminService_CreateAdmin0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAdminRequest
		if err := ctx.Bind(&in.Admin); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateAdmin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAdmin(ctx, req.(*CreateAdminRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Admin)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetAdmin0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAdminRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetAdmin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAdmin(ctx, req.(*GetAdminRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Admin)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListAdmins0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAdminsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListAdmins)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAdmins(ctx, req.(*ListAdminsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminSet)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateAdmin0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAdminRequest
		if err := ctx.Bind(&in.Admin); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateAdmin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAdmin(ctx, req.(*UpdateAdminRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Admin)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteAdmin0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAdminRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteAdmin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAdmin(ctx, req.(*DeleteAdminRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateRole0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRoleRequest
		if err := ctx.Bind(&in.Role); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRole(ctx, req.(*CreateRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Role)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetRole0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRole(ctx, req.(*GetRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Role)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListRoles0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRolesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoles(ctx, req.(*ListRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RoleSet)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateRole0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateRoleRequest
		if err := ctx.Bind(&in.Role); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateRole(ctx, req.(*UpdateRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Role)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteRole0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRole(ctx, req.(*DeleteRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateAdminRole0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAdminRoleRequest
		if err := ctx.Bind(&in.AdminRole); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateAdminRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAdminRole(ctx, req.(*CreateAdminRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminRole)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetAdminRole0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAdminRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetAdminRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAdminRole(ctx, req.(*GetAdminRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminRole)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListAdminRoles0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAdminRolesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListAdminRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAdminRoles(ctx, req.(*ListAdminRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminRoleSet)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateAdminRole0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAdminRoleRequest
		if err := ctx.Bind(&in.AdminRole); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateAdminRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAdminRole(ctx, req.(*UpdateAdminRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminRole)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteAdminRole0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAdminRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteAdminRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAdminRole(ctx, req.(*DeleteAdminRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreatePermission0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreatePermissionRequest
		if err := ctx.Bind(&in.Permission); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreatePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreatePermission(ctx, req.(*CreatePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Permission)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetPermission0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPermissionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetPermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPermission(ctx, req.(*GetPermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Permission)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListPermissions0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPermissionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListPermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPermissions(ctx, req.(*ListPermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PermissionSet)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdatePermission0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePermissionRequest
		if err := ctx.Bind(&in.Permission); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdatePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePermission(ctx, req.(*UpdatePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Permission)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeletePermission0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePermissionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeletePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePermission(ctx, req.(*DeletePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_CreateGroupPermission0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateGroupPermissionRequest
		if err := ctx.Bind(&in.GroupPermission); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceCreateGroupPermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateGroupPermission(ctx, req.(*CreateGroupPermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GroupPermission)
		return ctx.Result(200, reply)
	}
}

func _AdminService_GetGroupPermission0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGroupPermissionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceGetGroupPermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGroupPermission(ctx, req.(*GetGroupPermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GroupPermission)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListGroupPermissions0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGroupPermissionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListGroupPermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGroupPermissions(ctx, req.(*ListGroupPermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GroupPermissionSet)
		return ctx.Result(200, reply)
	}
}

func _AdminService_UpdateGroupPermission0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateGroupPermissionRequest
		if err := ctx.Bind(&in.GroupPermission); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceUpdateGroupPermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateGroupPermission(ctx, req.(*UpdateGroupPermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GroupPermission)
		return ctx.Result(200, reply)
	}
}

func _AdminService_DeleteGroupPermission0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteGroupPermissionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceDeleteGroupPermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteGroupPermission(ctx, req.(*DeleteGroupPermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListAdminOperationLogs0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAdminOperationLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListAdminOperationLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAdminOperationLogs(ctx, req.(*ListAdminOperationLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AdminOperationLogSet)
		return ctx.Result(200, reply)
	}
}

func _AdminService_ListSystemLogs0_HTTP_Handler(srv AdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSystemLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdminServiceListSystemLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSystemLogs(ctx, req.(*ListSystemLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SystemLogSet)
		return ctx.Result(200, reply)
	}
}

type AdminServiceHTTPClient interface {
	CreateAdmin(ctx context.Context, req *CreateAdminRequest, opts ...http.CallOption) (rsp *Admin, err error)
	CreateAdminRole(ctx context.Context, req *CreateAdminRoleRequest, opts ...http.CallOption) (rsp *AdminRole, err error)
	CreateGroupPermission(ctx context.Context, req *CreateGroupPermissionRequest, opts ...http.CallOption) (rsp *GroupPermission, err error)
	CreatePermission(ctx context.Context, req *CreatePermissionRequest, opts ...http.CallOption) (rsp *Permission, err error)
	CreateRole(ctx context.Context, req *CreateRoleRequest, opts ...http.CallOption) (rsp *Role, err error)
	DeleteAdmin(ctx context.Context, req *DeleteAdminRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteAdminRole(ctx context.Context, req *DeleteAdminRoleRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteGroupPermission(ctx context.Context, req *DeleteGroupPermissionRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeletePermission(ctx context.Context, req *DeletePermissionRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteRole(ctx context.Context, req *DeleteRoleRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetAdmin(ctx context.Context, req *GetAdminRequest, opts ...http.CallOption) (rsp *Admin, err error)
	GetAdminRole(ctx context.Context, req *GetAdminRoleRequest, opts ...http.CallOption) (rsp *AdminRole, err error)
	GetGroupPermission(ctx context.Context, req *GetGroupPermissionRequest, opts ...http.CallOption) (rsp *GroupPermission, err error)
	GetPermission(ctx context.Context, req *GetPermissionRequest, opts ...http.CallOption) (rsp *Permission, err error)
	GetRole(ctx context.Context, req *GetRoleRequest, opts ...http.CallOption) (rsp *Role, err error)
	ListAdminOperationLogs(ctx context.Context, req *ListAdminOperationLogsRequest, opts ...http.CallOption) (rsp *AdminOperationLogSet, err error)
	ListAdminRoles(ctx context.Context, req *ListAdminRolesRequest, opts ...http.CallOption) (rsp *AdminRoleSet, err error)
	ListAdmins(ctx context.Context, req *ListAdminsRequest, opts ...http.CallOption) (rsp *AdminSet, err error)
	ListGroupPermissions(ctx context.Context, req *ListGroupPermissionsRequest, opts ...http.CallOption) (rsp *GroupPermissionSet, err error)
	ListPermissions(ctx context.Context, req *ListPermissionsRequest, opts ...http.CallOption) (rsp *PermissionSet, err error)
	ListRoles(ctx context.Context, req *ListRolesRequest, opts ...http.CallOption) (rsp *RoleSet, err error)
	ListSystemLogs(ctx context.Context, req *ListSystemLogsRequest, opts ...http.CallOption) (rsp *SystemLogSet, err error)
	UpdateAdmin(ctx context.Context, req *UpdateAdminRequest, opts ...http.CallOption) (rsp *Admin, err error)
	UpdateAdminRole(ctx context.Context, req *UpdateAdminRoleRequest, opts ...http.CallOption) (rsp *AdminRole, err error)
	UpdateGroupPermission(ctx context.Context, req *UpdateGroupPermissionRequest, opts ...http.CallOption) (rsp *GroupPermission, err error)
	UpdatePermission(ctx context.Context, req *UpdatePermissionRequest, opts ...http.CallOption) (rsp *Permission, err error)
	UpdateRole(ctx context.Context, req *UpdateRoleRequest, opts ...http.CallOption) (rsp *Role, err error)
}

type AdminServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminServiceHTTPClient(client *http.Client) AdminServiceHTTPClient {
	return &AdminServiceHTTPClientImpl{client}
}

func (c *AdminServiceHTTPClientImpl) CreateAdmin(ctx context.Context, in *CreateAdminRequest, opts ...http.CallOption) (*Admin, error) {
	var out Admin
	pattern := "/v1/admins/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("admin"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateAdmin),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Admin, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) CreateAdminRole(ctx context.Context, in *CreateAdminRoleRequest, opts ...http.CallOption) (*AdminRole, error) {
	var out AdminRole
	pattern := "/v1/admin-roles/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("adminRole"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateAdminRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.AdminRole, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) CreateGroupPermission(ctx context.Context, in *CreateGroupPermissionRequest, opts ...http.CallOption) (*GroupPermission, error) {
	var out GroupPermission
	pattern := "/v1/group-permissions/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("groupPermission"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateGroupPermission),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.GroupPermission, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...http.CallOption) (*Permission, error) {
	var out Permission
	pattern := "/v1/permissions/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("permission"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreatePermission),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Permission, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...http.CallOption) (*Role, error) {
	var out Role
	pattern := "/v1/roles/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("role"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceCreateRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Role, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteAdmin(ctx context.Context, in *DeleteAdminRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admins/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteAdmin),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteAdminRole(ctx context.Context, in *DeleteAdminRoleRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/admin-roles/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteAdminRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteGroupPermission(ctx context.Context, in *DeleteGroupPermissionRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/group-permissions/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteGroupPermission),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeletePermission(ctx context.Context, in *DeletePermissionRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/permissions/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeletePermission),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/roles/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceDeleteRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetAdmin(ctx context.Context, in *GetAdminRequest, opts ...http.CallOption) (*Admin, error) {
	var out Admin
	pattern := "/v1/admins/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetAdmin),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetAdminRole(ctx context.Context, in *GetAdminRoleRequest, opts ...http.CallOption) (*AdminRole, error) {
	var out AdminRole
	pattern := "/v1/admin-roles/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetAdminRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetGroupPermission(ctx context.Context, in *GetGroupPermissionRequest, opts ...http.CallOption) (*GroupPermission, error) {
	var out GroupPermission
	pattern := "/v1/group-permissions/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetGroupPermission),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetPermission(ctx context.Context, in *GetPermissionRequest, opts ...http.CallOption) (*Permission, error) {
	var out Permission
	pattern := "/v1/permissions/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetPermission),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) GetRole(ctx context.Context, in *GetRoleRequest, opts ...http.CallOption) (*Role, error) {
	var out Role
	pattern := "/v1/roles/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceGetRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListAdminOperationLogs(ctx context.Context, in *ListAdminOperationLogsRequest, opts ...http.CallOption) (*AdminOperationLogSet, error) {
	var out AdminOperationLogSet
	pattern := "/v1/admin-operation-logs"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListAdminOperationLogs),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListAdminRoles(ctx context.Context, in *ListAdminRolesRequest, opts ...http.CallOption) (*AdminRoleSet, error) {
	var out AdminRoleSet
	pattern := "/v1/admin-roles"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListAdminRoles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListAdmins(ctx context.Context, in *ListAdminsRequest, opts ...http.CallOption) (*AdminSet, error) {
	var out AdminSet
	pattern := "/v1/admins"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListAdmins),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListGroupPermissions(ctx context.Context, in *ListGroupPermissionsRequest, opts ...http.CallOption) (*GroupPermissionSet, error) {
	var out GroupPermissionSet
	pattern := "/v1/group-permissions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListGroupPermissions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...http.CallOption) (*PermissionSet, error) {
	var out PermissionSet
	pattern := "/v1/permissions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListPermissions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...http.CallOption) (*RoleSet, error) {
	var out RoleSet
	pattern := "/v1/roles"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListRoles),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) ListSystemLogs(ctx context.Context, in *ListSystemLogsRequest, opts ...http.CallOption) (*SystemLogSet, error) {
	var out SystemLogSet
	pattern := "/v1/system-logs"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationAdminServiceListSystemLogs),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateAdmin(ctx context.Context, in *UpdateAdminRequest, opts ...http.CallOption) (*Admin, error) {
	var out Admin
	pattern := "/v1/admins/update"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("admin"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateAdmin),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in.Admin, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateAdminRole(ctx context.Context, in *UpdateAdminRoleRequest, opts ...http.CallOption) (*AdminRole, error) {
	var out AdminRole
	pattern := "/v1/admin-roles/update"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("adminRole"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateAdminRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in.AdminRole, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateGroupPermission(ctx context.Context, in *UpdateGroupPermissionRequest, opts ...http.CallOption) (*GroupPermission, error) {
	var out GroupPermission
	pattern := "/v1/group-permissions/update"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("groupPermission"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateGroupPermission),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in.GroupPermission, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdatePermission(ctx context.Context, in *UpdatePermissionRequest, opts ...http.CallOption) (*Permission, error) {
	var out Permission
	pattern := "/v1/permissions/update"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("permission"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdatePermission),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in.Permission, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AdminServiceHTTPClientImpl) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...http.CallOption) (*Role, error) {
	var out Role
	pattern := "/v1/roles/update"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("role"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationAdminServiceUpdateRole),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in.Role, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
