// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: admin/v1/admin.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Admin struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username          string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password          string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	RealName          string                 `protobuf:"bytes,4,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	RoleId            int64                  `protobuf:"varint,5,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Status            uint32                 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	LastLoginTime     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`
	PasswordUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=password_updated_at,json=passwordUpdatedAt,proto3" json:"password_updated_at,omitempty"`
	Remark            string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateTime        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Admin) Reset() {
	*x = Admin{}
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Admin) ProtoMessage() {}

func (x *Admin) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Admin.ProtoReflect.Descriptor instead.
func (*Admin) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Admin) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Admin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Admin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Admin) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *Admin) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *Admin) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Admin) GetLastLoginTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLoginTime
	}
	return nil
}

func (x *Admin) GetPasswordUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PasswordUpdatedAt
	}
	return nil
}

func (x *Admin) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Admin) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Admin) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type AdminSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admins        []*Admin               `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSet) Reset() {
	*x = AdminSet{}
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSet) ProtoMessage() {}

func (x *AdminSet) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSet.ProtoReflect.Descriptor instead.
func (*AdminSet) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminSet) GetAdmins() []*Admin {
	if x != nil {
		return x.Admins
	}
	return nil
}

func (x *AdminSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *Admin                 `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRequest) Reset() {
	*x = CreateAdminRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRequest) ProtoMessage() {}

func (x *CreateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAdminRequest) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type GetAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminRequest) Reset() {
	*x = GetAdminRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminRequest) ProtoMessage() {}

func (x *GetAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminRequest.ProtoReflect.Descriptor instead.
func (*GetAdminRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdminRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListAdminsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminsRequest) Reset() {
	*x = ListAdminsRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminsRequest) ProtoMessage() {}

func (x *ListAdminsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminsRequest.ProtoReflect.Descriptor instead.
func (*ListAdminsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListAdminsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdminsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAdminsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListAdminsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type UpdateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *Admin                 `protobuf:"bytes,1,opt,name=admin,proto3" json:"admin,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminRequest) Reset() {
	*x = UpdateAdminRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminRequest) ProtoMessage() {}

func (x *UpdateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdminRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAdminRequest) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *UpdateAdminRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminRequest) Reset() {
	*x = DeleteAdminRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminRequest) ProtoMessage() {}

func (x *DeleteAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdminRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAdminRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *Role) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Role) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type RoleSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleSet) Reset() {
	*x = RoleSet{}
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleSet) ProtoMessage() {}

func (x *RoleSet) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleSet.ProtoReflect.Descriptor instead.
func (*RoleSet) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *RoleSet) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *RoleSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *CreateRoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *GetRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ListRolesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRolesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRolesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListRolesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *UpdateRoleRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdminRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AdminId       int64                  `protobuf:"varint,2,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	RoleId        int64                  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRole) Reset() {
	*x = AdminRole{}
	mi := &file_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRole) ProtoMessage() {}

func (x *AdminRole) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRole.ProtoReflect.Descriptor instead.
func (*AdminRole) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *AdminRole) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminRole) GetAdminId() int64 {
	if x != nil {
		return x.AdminId
	}
	return 0
}

func (x *AdminRole) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AdminRole) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *AdminRole) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type AdminRoleSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminRoles    []*AdminRole           `protobuf:"bytes,1,rep,name=admin_roles,json=adminRoles,proto3" json:"admin_roles,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRoleSet) Reset() {
	*x = AdminRoleSet{}
	mi := &file_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRoleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRoleSet) ProtoMessage() {}

func (x *AdminRoleSet) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRoleSet.ProtoReflect.Descriptor instead.
func (*AdminRoleSet) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *AdminRoleSet) GetAdminRoles() []*AdminRole {
	if x != nil {
		return x.AdminRoles
	}
	return nil
}

func (x *AdminRoleSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateAdminRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminRole     *AdminRole             `protobuf:"bytes,1,opt,name=admin_role,json=adminRole,proto3" json:"admin_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRoleRequest) Reset() {
	*x = CreateAdminRoleRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRoleRequest) ProtoMessage() {}

func (x *CreateAdminRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *CreateAdminRoleRequest) GetAdminRole() *AdminRole {
	if x != nil {
		return x.AdminRole
	}
	return nil
}

type GetAdminRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminRoleRequest) Reset() {
	*x = GetAdminRoleRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminRoleRequest) ProtoMessage() {}

func (x *GetAdminRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminRoleRequest.ProtoReflect.Descriptor instead.
func (*GetAdminRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *GetAdminRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListAdminRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdminRolesRequest) Reset() {
	*x = ListAdminRolesRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdminRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdminRolesRequest) ProtoMessage() {}

func (x *ListAdminRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdminRolesRequest.ProtoReflect.Descriptor instead.
func (*ListAdminRolesRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *ListAdminRolesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdminRolesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAdminRolesRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListAdminRolesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type UpdateAdminRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminRole     *AdminRole             `protobuf:"bytes,1,opt,name=admin_role,json=adminRole,proto3" json:"admin_role,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdminRoleRequest) Reset() {
	*x = UpdateAdminRoleRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdminRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdminRoleRequest) ProtoMessage() {}

func (x *UpdateAdminRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdminRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdminRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateAdminRoleRequest) GetAdminRole() *AdminRole {
	if x != nil {
		return x.AdminRole
	}
	return nil
}

func (x *UpdateAdminRoleRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteAdminRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminRoleRequest) Reset() {
	*x = DeleteAdminRoleRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminRoleRequest) ProtoMessage() {}

func (x *DeleteAdminRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdminRoleRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteAdminRoleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Handle        string                 `protobuf:"bytes,4,opt,name=handle,proto3" json:"handle,omitempty"`
	Weight        int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_admin_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *Permission) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Permission) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Permission) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Permission) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Permission) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Permission) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Permission) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type PermissionSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*Permission          `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionSet) Reset() {
	*x = PermissionSet{}
	mi := &file_admin_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionSet) ProtoMessage() {}

func (x *PermissionSet) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionSet.ProtoReflect.Descriptor instead.
func (*PermissionSet) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *PermissionSet) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *PermissionSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *CreatePermissionRequest) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type GetPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionRequest) Reset() {
	*x = GetPermissionRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequest) ProtoMessage() {}

func (x *GetPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *GetPermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsRequest) Reset() {
	*x = ListPermissionsRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsRequest) ProtoMessage() {}

func (x *ListPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *ListPermissionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPermissionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListPermissionsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListPermissionsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type UpdatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *UpdatePermissionRequest) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

func (x *UpdatePermissionRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeletePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{27}
}

func (x *DeletePermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GroupPermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PermissionId  int64                  `protobuf:"varint,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPermission) Reset() {
	*x = GroupPermission{}
	mi := &file_admin_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPermission) ProtoMessage() {}

func (x *GroupPermission) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPermission.ProtoReflect.Descriptor instead.
func (*GroupPermission) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *GroupPermission) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupPermission) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupPermission) GetPermissionId() int64 {
	if x != nil {
		return x.PermissionId
	}
	return 0
}

func (x *GroupPermission) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *GroupPermission) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type GroupPermissionSet struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupPermissions []*GroupPermission     `protobuf:"bytes,1,rep,name=group_permissions,json=groupPermissions,proto3" json:"group_permissions,omitempty"`
	NextPageToken    string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupPermissionSet) Reset() {
	*x = GroupPermissionSet{}
	mi := &file_admin_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPermissionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPermissionSet) ProtoMessage() {}

func (x *GroupPermissionSet) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPermissionSet.ProtoReflect.Descriptor instead.
func (*GroupPermissionSet) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *GroupPermissionSet) GetGroupPermissions() []*GroupPermission {
	if x != nil {
		return x.GroupPermissions
	}
	return nil
}

func (x *GroupPermissionSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateGroupPermissionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupPermission *GroupPermission       `protobuf:"bytes,1,opt,name=group_permission,json=groupPermission,proto3" json:"group_permission,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGroupPermissionRequest) Reset() {
	*x = CreateGroupPermissionRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupPermissionRequest) ProtoMessage() {}

func (x *CreateGroupPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupPermissionRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupPermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{30}
}

func (x *CreateGroupPermissionRequest) GetGroupPermission() *GroupPermission {
	if x != nil {
		return x.GroupPermission
	}
	return nil
}

type GetGroupPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupPermissionRequest) Reset() {
	*x = GetGroupPermissionRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupPermissionRequest) ProtoMessage() {}

func (x *GetGroupPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupPermissionRequest.ProtoReflect.Descriptor instead.
func (*GetGroupPermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{31}
}

func (x *GetGroupPermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListGroupPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupPermissionsRequest) Reset() {
	*x = ListGroupPermissionsRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupPermissionsRequest) ProtoMessage() {}

func (x *ListGroupPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupPermissionsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{32}
}

func (x *ListGroupPermissionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGroupPermissionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListGroupPermissionsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListGroupPermissionsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type UpdateGroupPermissionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupPermission *GroupPermission       `protobuf:"bytes,1,opt,name=group_permission,json=groupPermission,proto3" json:"group_permission,omitempty"`
	UpdateMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateGroupPermissionRequest) Reset() {
	*x = UpdateGroupPermissionRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupPermissionRequest) ProtoMessage() {}

func (x *UpdateGroupPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupPermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupPermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateGroupPermissionRequest) GetGroupPermission() *GroupPermission {
	if x != nil {
		return x.GroupPermission
	}
	return nil
}

func (x *UpdateGroupPermissionRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteGroupPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupPermissionRequest) Reset() {
	*x = DeleteGroupPermissionRequest{}
	mi := &file_admin_v1_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupPermissionRequest) ProtoMessage() {}

func (x *DeleteGroupPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_v1_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupPermissionRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupPermissionRequest) Descriptor() ([]byte, []int) {
	return file_admin_v1_admin_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteGroupPermissionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_admin_v1_admin_proto protoreflect.FileDescriptor

const file_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x14admin/v1/admin.proto\x12\badmin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x03\n" +
	"\x05Admin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1b\n" +
	"\treal_name\x18\x04 \x01(\tR\brealName\x12\x17\n" +
	"\arole_id\x18\x05 \x01(\x03R\x06roleId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\rR\x06status\x12B\n" +
	"\x0flast_login_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rlastLoginTime\x12J\n" +
	"\x13password_updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11passwordUpdatedAt\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12;\n" +
	"\vcreate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"[\n" +
	"\bAdminSet\x12'\n" +
	"\x06admins\x18\x01 \x03(\v2\x0f.admin.v1.AdminR\x06admins\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"@\n" +
	"\x12CreateAdminRequest\x12*\n" +
	"\x05admin\x18\x01 \x01(\v2\x0f.admin.v1.AdminB\x03\xe0A\x02R\x05admin\"&\n" +
	"\x0fGetAdminRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x82\x01\n" +
	"\x11ListAdminsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"\x82\x01\n" +
	"\x12UpdateAdminRequest\x12*\n" +
	"\x05admin\x18\x01 \x01(\v2\x0f.admin.v1.AdminB\x03\xe0A\x02R\x05admin\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\")\n" +
	"\x12DeleteAdminRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\xad\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"W\n" +
	"\aRoleSet\x12$\n" +
	"\x05roles\x18\x01 \x03(\v2\x0e.admin.v1.RoleR\x05roles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"<\n" +
	"\x11CreateRoleRequest\x12'\n" +
	"\x04role\x18\x01 \x01(\v2\x0e.admin.v1.RoleB\x03\xe0A\x02R\x04role\"%\n" +
	"\x0eGetRoleRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x81\x01\n" +
	"\x10ListRolesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"~\n" +
	"\x11UpdateRoleRequest\x12'\n" +
	"\x04role\x18\x01 \x01(\v2\x0e.admin.v1.RoleB\x03\xe0A\x02R\x04role\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"(\n" +
	"\x11DeleteRoleRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\xc9\x01\n" +
	"\tAdminRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\badmin_id\x18\x02 \x01(\x03R\aadminId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x03R\x06roleId\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"l\n" +
	"\fAdminRoleSet\x124\n" +
	"\vadmin_roles\x18\x01 \x03(\v2\x13.admin.v1.AdminRoleR\n" +
	"adminRoles\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"Q\n" +
	"\x16CreateAdminRoleRequest\x127\n" +
	"\n" +
	"admin_role\x18\x01 \x01(\v2\x13.admin.v1.AdminRoleB\x03\xe0A\x02R\tadminRole\"*\n" +
	"\x13GetAdminRoleRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x86\x01\n" +
	"\x15ListAdminRolesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"\x93\x01\n" +
	"\x16UpdateAdminRoleRequest\x127\n" +
	"\n" +
	"admin_role\x18\x01 \x01(\v2\x13.admin.v1.AdminRoleB\x03\xe0A\x02R\tadminRole\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"-\n" +
	"\x16DeleteAdminRoleRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\xf9\x01\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06handle\x18\x04 \x01(\tR\x06handle\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"o\n" +
	"\rPermissionSet\x126\n" +
	"\vpermissions\x18\x01 \x03(\v2\x14.admin.v1.PermissionR\vpermissions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"T\n" +
	"\x17CreatePermissionRequest\x129\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x14.admin.v1.PermissionB\x03\xe0A\x02R\n" +
	"permission\"+\n" +
	"\x14GetPermissionRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x87\x01\n" +
	"\x16ListPermissionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"\x96\x01\n" +
	"\x17UpdatePermissionRequest\x129\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x14.admin.v1.PermissionB\x03\xe0A\x02R\n" +
	"permission\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\".\n" +
	"\x17DeletePermissionRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\xdb\x01\n" +
	"\x0fGroupPermission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12#\n" +
	"\rpermission_id\x18\x03 \x01(\x03R\fpermissionId\x12;\n" +
	"\vcreate_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"\x84\x01\n" +
	"\x12GroupPermissionSet\x12F\n" +
	"\x11group_permissions\x18\x01 \x03(\v2\x19.admin.v1.GroupPermissionR\x10groupPermissions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"i\n" +
	"\x1cCreateGroupPermissionRequest\x12I\n" +
	"\x10group_permission\x18\x01 \x01(\v2\x19.admin.v1.GroupPermissionB\x03\xe0A\x02R\x0fgroupPermission\"0\n" +
	"\x19GetGroupPermissionRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x8c\x01\n" +
	"\x1bListGroupPermissionsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"\xab\x01\n" +
	"\x1cUpdateGroupPermissionRequest\x12I\n" +
	"\x10group_permission\x18\x01 \x01(\v2\x19.admin.v1.GroupPermissionB\x03\xe0A\x02R\x0fgroupPermission\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"3\n" +
	"\x1cDeleteGroupPermissionRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id2\xe2\x14\n" +
	"\fAdminService\x12^\n" +
	"\vCreateAdmin\x12\x1c.admin.v1.CreateAdminRequest\x1a\x0f.admin.v1.Admin\" \x82\xd3\xe4\x93\x02\x1a:\x05admin\"\x11/v1/admins/create\x12O\n" +
	"\bGetAdmin\x12\x19.admin.v1.GetAdminRequest\x1a\x0f.admin.v1.Admin\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/admins/{id}\x12Q\n" +
	"\n" +
	"ListAdmins\x12\x1b.admin.v1.ListAdminsRequest\x1a\x12.admin.v1.AdminSet\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/admins\x12^\n" +
	"\vUpdateAdmin\x12\x1c.admin.v1.UpdateAdminRequest\x1a\x0f.admin.v1.Admin\" \x82\xd3\xe4\x93\x02\x1a:\x05admin\x1a\x11/v1/admins/update\x12\\\n" +
	"\vDeleteAdmin\x12\x1c.admin.v1.DeleteAdminRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/admins/{id}\x12Y\n" +
	"\n" +
	"CreateRole\x12\x1b.admin.v1.CreateRoleRequest\x1a\x0e.admin.v1.Role\"\x1e\x82\xd3\xe4\x93\x02\x18:\x04role\"\x10/v1/roles/create\x12K\n" +
	"\aGetRole\x12\x18.admin.v1.GetRoleRequest\x1a\x0e.admin.v1.Role\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/roles/{id}\x12M\n" +
	"\tListRoles\x12\x1a.admin.v1.ListRolesRequest\x1a\x11.admin.v1.RoleSet\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/roles\x12Y\n" +
	"\n" +
	"UpdateRole\x12\x1b.admin.v1.UpdateRoleRequest\x1a\x0e.admin.v1.Role\"\x1e\x82\xd3\xe4\x93\x02\x18:\x04role\x1a\x10/v1/roles/update\x12Y\n" +
	"\n" +
	"DeleteRole\x12\x1b.admin.v1.DeleteRoleRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/roles/{id}\x12t\n" +
	"\x0fCreateAdminRole\x12 .admin.v1.CreateAdminRoleRequest\x1a\x13.admin.v1.AdminRole\"*\x82\xd3\xe4\x93\x02$:\n" +
	"admin_role\"\x16/v1/admin-roles/create\x12`\n" +
	"\fGetAdminRole\x12\x1d.admin.v1.GetAdminRoleRequest\x1a\x13.admin.v1.AdminRole\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/admin-roles/{id}\x12b\n" +
	"\x0eListAdminRoles\x12\x1f.admin.v1.ListAdminRolesRequest\x1a\x16.admin.v1.AdminRoleSet\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/admin-roles\x12t\n" +
	"\x0fUpdateAdminRole\x12 .admin.v1.UpdateAdminRoleRequest\x1a\x13.admin.v1.AdminRole\"*\x82\xd3\xe4\x93\x02$:\n" +
	"admin_role\x1a\x16/v1/admin-roles/update\x12i\n" +
	"\x0fDeleteAdminRole\x12 .admin.v1.DeleteAdminRoleRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/admin-roles/{id}\x12w\n" +
	"\x10CreatePermission\x12!.admin.v1.CreatePermissionRequest\x1a\x14.admin.v1.Permission\"*\x82\xd3\xe4\x93\x02$:\n" +
	"permission\"\x16/v1/permissions/create\x12c\n" +
	"\rGetPermission\x12\x1e.admin.v1.GetPermissionRequest\x1a\x14.admin.v1.Permission\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/permissions/{id}\x12e\n" +
	"\x0fListPermissions\x12 .admin.v1.ListPermissionsRequest\x1a\x17.admin.v1.PermissionSet\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/permissions\x12w\n" +
	"\x10UpdatePermission\x12!.admin.v1.UpdatePermissionRequest\x1a\x14.admin.v1.Permission\"*\x82\xd3\xe4\x93\x02$:\n" +
	"permission\x1a\x16/v1/permissions/update\x12k\n" +
	"\x10DeletePermission\x12!.admin.v1.DeletePermissionRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/permissions/{id}\x12\x92\x01\n" +
	"\x15CreateGroupPermission\x12&.admin.v1.CreateGroupPermissionRequest\x1a\x19.admin.v1.GroupPermission\"6\x82\xd3\xe4\x93\x020:\x10group_permission\"\x1c/v1/group-permissions/create\x12x\n" +
	"\x12GetGroupPermission\x12#.admin.v1.GetGroupPermissionRequest\x1a\x19.admin.v1.GroupPermission\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/group-permissions/{id}\x12z\n" +
	"\x14ListGroupPermissions\x12%.admin.v1.ListGroupPermissionsRequest\x1a\x1c.admin.v1.GroupPermissionSet\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/group-permissions\x12\x92\x01\n" +
	"\x15UpdateGroupPermission\x12&.admin.v1.UpdateGroupPermissionRequest\x1a\x19.admin.v1.GroupPermission\"6\x82\xd3\xe4\x93\x020:\x10group_permission\x1a\x1c/v1/group-permissions/update\x12{\n" +
	"\x15DeleteGroupPermission\x12&.admin.v1.DeleteGroupPermissionRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/group-permissions/{id}B?\n" +
	"\x19io.grpc.examples.admin.v1B\n" +
	"AdminProtoP\x01Z\x14crow/api/admin/v1;v1b\x06proto3"

var (
	file_admin_v1_admin_proto_rawDescOnce sync.Once
	file_admin_v1_admin_proto_rawDescData []byte
)

func file_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)))
	})
	return file_admin_v1_admin_proto_rawDescData
}

var file_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_admin_v1_admin_proto_goTypes = []any{
	(*Admin)(nil),                        // 0: admin.v1.Admin
	(*AdminSet)(nil),                     // 1: admin.v1.AdminSet
	(*CreateAdminRequest)(nil),           // 2: admin.v1.CreateAdminRequest
	(*GetAdminRequest)(nil),              // 3: admin.v1.GetAdminRequest
	(*ListAdminsRequest)(nil),            // 4: admin.v1.ListAdminsRequest
	(*UpdateAdminRequest)(nil),           // 5: admin.v1.UpdateAdminRequest
	(*DeleteAdminRequest)(nil),           // 6: admin.v1.DeleteAdminRequest
	(*Role)(nil),                         // 7: admin.v1.Role
	(*RoleSet)(nil),                      // 8: admin.v1.RoleSet
	(*CreateRoleRequest)(nil),            // 9: admin.v1.CreateRoleRequest
	(*GetRoleRequest)(nil),               // 10: admin.v1.GetRoleRequest
	(*ListRolesRequest)(nil),             // 11: admin.v1.ListRolesRequest
	(*UpdateRoleRequest)(nil),            // 12: admin.v1.UpdateRoleRequest
	(*DeleteRoleRequest)(nil),            // 13: admin.v1.DeleteRoleRequest
	(*AdminRole)(nil),                    // 14: admin.v1.AdminRole
	(*AdminRoleSet)(nil),                 // 15: admin.v1.AdminRoleSet
	(*CreateAdminRoleRequest)(nil),       // 16: admin.v1.CreateAdminRoleRequest
	(*GetAdminRoleRequest)(nil),          // 17: admin.v1.GetAdminRoleRequest
	(*ListAdminRolesRequest)(nil),        // 18: admin.v1.ListAdminRolesRequest
	(*UpdateAdminRoleRequest)(nil),       // 19: admin.v1.UpdateAdminRoleRequest
	(*DeleteAdminRoleRequest)(nil),       // 20: admin.v1.DeleteAdminRoleRequest
	(*Permission)(nil),                   // 21: admin.v1.Permission
	(*PermissionSet)(nil),                // 22: admin.v1.PermissionSet
	(*CreatePermissionRequest)(nil),      // 23: admin.v1.CreatePermissionRequest
	(*GetPermissionRequest)(nil),         // 24: admin.v1.GetPermissionRequest
	(*ListPermissionsRequest)(nil),       // 25: admin.v1.ListPermissionsRequest
	(*UpdatePermissionRequest)(nil),      // 26: admin.v1.UpdatePermissionRequest
	(*DeletePermissionRequest)(nil),      // 27: admin.v1.DeletePermissionRequest
	(*GroupPermission)(nil),              // 28: admin.v1.GroupPermission
	(*GroupPermissionSet)(nil),           // 29: admin.v1.GroupPermissionSet
	(*CreateGroupPermissionRequest)(nil), // 30: admin.v1.CreateGroupPermissionRequest
	(*GetGroupPermissionRequest)(nil),    // 31: admin.v1.GetGroupPermissionRequest
	(*ListGroupPermissionsRequest)(nil),  // 32: admin.v1.ListGroupPermissionsRequest
	(*UpdateGroupPermissionRequest)(nil), // 33: admin.v1.UpdateGroupPermissionRequest
	(*DeleteGroupPermissionRequest)(nil), // 34: admin.v1.DeleteGroupPermissionRequest
	(*timestamppb.Timestamp)(nil),        // 35: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),        // 36: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                // 37: google.protobuf.Empty
}
var file_admin_v1_admin_proto_depIdxs = []int32{
	35, // 0: admin.v1.Admin.last_login_time:type_name -> google.protobuf.Timestamp
	35, // 1: admin.v1.Admin.password_updated_at:type_name -> google.protobuf.Timestamp
	35, // 2: admin.v1.Admin.create_time:type_name -> google.protobuf.Timestamp
	35, // 3: admin.v1.Admin.update_time:type_name -> google.protobuf.Timestamp
	0,  // 4: admin.v1.AdminSet.admins:type_name -> admin.v1.Admin
	0,  // 5: admin.v1.CreateAdminRequest.admin:type_name -> admin.v1.Admin
	0,  // 6: admin.v1.UpdateAdminRequest.admin:type_name -> admin.v1.Admin
	36, // 7: admin.v1.UpdateAdminRequest.update_mask:type_name -> google.protobuf.FieldMask
	35, // 8: admin.v1.Role.create_time:type_name -> google.protobuf.Timestamp
	35, // 9: admin.v1.Role.update_time:type_name -> google.protobuf.Timestamp
	7,  // 10: admin.v1.RoleSet.roles:type_name -> admin.v1.Role
	7,  // 11: admin.v1.CreateRoleRequest.role:type_name -> admin.v1.Role
	7,  // 12: admin.v1.UpdateRoleRequest.role:type_name -> admin.v1.Role
	36, // 13: admin.v1.UpdateRoleRequest.update_mask:type_name -> google.protobuf.FieldMask
	35, // 14: admin.v1.AdminRole.create_time:type_name -> google.protobuf.Timestamp
	35, // 15: admin.v1.AdminRole.update_time:type_name -> google.protobuf.Timestamp
	14, // 16: admin.v1.AdminRoleSet.admin_roles:type_name -> admin.v1.AdminRole
	14, // 17: admin.v1.CreateAdminRoleRequest.admin_role:type_name -> admin.v1.AdminRole
	14, // 18: admin.v1.UpdateAdminRoleRequest.admin_role:type_name -> admin.v1.AdminRole
	36, // 19: admin.v1.UpdateAdminRoleRequest.update_mask:type_name -> google.protobuf.FieldMask
	35, // 20: admin.v1.Permission.create_time:type_name -> google.protobuf.Timestamp
	35, // 21: admin.v1.Permission.update_time:type_name -> google.protobuf.Timestamp
	21, // 22: admin.v1.PermissionSet.permissions:type_name -> admin.v1.Permission
	21, // 23: admin.v1.CreatePermissionRequest.permission:type_name -> admin.v1.Permission
	21, // 24: admin.v1.UpdatePermissionRequest.permission:type_name -> admin.v1.Permission
	36, // 25: admin.v1.UpdatePermissionRequest.update_mask:type_name -> google.protobuf.FieldMask
	35, // 26: admin.v1.GroupPermission.create_time:type_name -> google.protobuf.Timestamp
	35, // 27: admin.v1.GroupPermission.update_time:type_name -> google.protobuf.Timestamp
	28, // 28: admin.v1.GroupPermissionSet.group_permissions:type_name -> admin.v1.GroupPermission
	28, // 29: admin.v1.CreateGroupPermissionRequest.group_permission:type_name -> admin.v1.GroupPermission
	28, // 30: admin.v1.UpdateGroupPermissionRequest.group_permission:type_name -> admin.v1.GroupPermission
	36, // 31: admin.v1.UpdateGroupPermissionRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 32: admin.v1.AdminService.CreateAdmin:input_type -> admin.v1.CreateAdminRequest
	3,  // 33: admin.v1.AdminService.GetAdmin:input_type -> admin.v1.GetAdminRequest
	4,  // 34: admin.v1.AdminService.ListAdmins:input_type -> admin.v1.ListAdminsRequest
	5,  // 35: admin.v1.AdminService.UpdateAdmin:input_type -> admin.v1.UpdateAdminRequest
	6,  // 36: admin.v1.AdminService.DeleteAdmin:input_type -> admin.v1.DeleteAdminRequest
	9,  // 37: admin.v1.AdminService.CreateRole:input_type -> admin.v1.CreateRoleRequest
	10, // 38: admin.v1.AdminService.GetRole:input_type -> admin.v1.GetRoleRequest
	11, // 39: admin.v1.AdminService.ListRoles:input_type -> admin.v1.ListRolesRequest
	12, // 40: admin.v1.AdminService.UpdateRole:input_type -> admin.v1.UpdateRoleRequest
	13, // 41: admin.v1.AdminService.DeleteRole:input_type -> admin.v1.DeleteRoleRequest
	16, // 42: admin.v1.AdminService.CreateAdminRole:input_type -> admin.v1.CreateAdminRoleRequest
	17, // 43: admin.v1.AdminService.GetAdminRole:input_type -> admin.v1.GetAdminRoleRequest
	18, // 44: admin.v1.AdminService.ListAdminRoles:input_type -> admin.v1.ListAdminRolesRequest
	19, // 45: admin.v1.AdminService.UpdateAdminRole:input_type -> admin.v1.UpdateAdminRoleRequest
	20, // 46: admin.v1.AdminService.DeleteAdminRole:input_type -> admin.v1.DeleteAdminRoleRequest
	23, // 47: admin.v1.AdminService.CreatePermission:input_type -> admin.v1.CreatePermissionRequest
	24, // 48: admin.v1.AdminService.GetPermission:input_type -> admin.v1.GetPermissionRequest
	25, // 49: admin.v1.AdminService.ListPermissions:input_type -> admin.v1.ListPermissionsRequest
	26, // 50: admin.v1.AdminService.UpdatePermission:input_type -> admin.v1.UpdatePermissionRequest
	27, // 51: admin.v1.AdminService.DeletePermission:input_type -> admin.v1.DeletePermissionRequest
	30, // 52: admin.v1.AdminService.CreateGroupPermission:input_type -> admin.v1.CreateGroupPermissionRequest
	31, // 53: admin.v1.AdminService.GetGroupPermission:input_type -> admin.v1.GetGroupPermissionRequest
	32, // 54: admin.v1.AdminService.ListGroupPermissions:input_type -> admin.v1.ListGroupPermissionsRequest
	33, // 55: admin.v1.AdminService.UpdateGroupPermission:input_type -> admin.v1.UpdateGroupPermissionRequest
	34, // 56: admin.v1.AdminService.DeleteGroupPermission:input_type -> admin.v1.DeleteGroupPermissionRequest
	0,  // 57: admin.v1.AdminService.CreateAdmin:output_type -> admin.v1.Admin
	0,  // 58: admin.v1.AdminService.GetAdmin:output_type -> admin.v1.Admin
	1,  // 59: admin.v1.AdminService.ListAdmins:output_type -> admin.v1.AdminSet
	0,  // 60: admin.v1.AdminService.UpdateAdmin:output_type -> admin.v1.Admin
	37, // 61: admin.v1.AdminService.DeleteAdmin:output_type -> google.protobuf.Empty
	7,  // 62: admin.v1.AdminService.CreateRole:output_type -> admin.v1.Role
	7,  // 63: admin.v1.AdminService.GetRole:output_type -> admin.v1.Role
	8,  // 64: admin.v1.AdminService.ListRoles:output_type -> admin.v1.RoleSet
	7,  // 65: admin.v1.AdminService.UpdateRole:output_type -> admin.v1.Role
	37, // 66: admin.v1.AdminService.DeleteRole:output_type -> google.protobuf.Empty
	14, // 67: admin.v1.AdminService.CreateAdminRole:output_type -> admin.v1.AdminRole
	14, // 68: admin.v1.AdminService.GetAdminRole:output_type -> admin.v1.AdminRole
	15, // 69: admin.v1.AdminService.ListAdminRoles:output_type -> admin.v1.AdminRoleSet
	14, // 70: admin.v1.AdminService.UpdateAdminRole:output_type -> admin.v1.AdminRole
	37, // 71: admin.v1.AdminService.DeleteAdminRole:output_type -> google.protobuf.Empty
	21, // 72: admin.v1.AdminService.CreatePermission:output_type -> admin.v1.Permission
	21, // 73: admin.v1.AdminService.GetPermission:output_type -> admin.v1.Permission
	22, // 74: admin.v1.AdminService.ListPermissions:output_type -> admin.v1.PermissionSet
	21, // 75: admin.v1.AdminService.UpdatePermission:output_type -> admin.v1.Permission
	37, // 76: admin.v1.AdminService.DeletePermission:output_type -> google.protobuf.Empty
	28, // 77: admin.v1.AdminService.CreateGroupPermission:output_type -> admin.v1.GroupPermission
	28, // 78: admin.v1.AdminService.GetGroupPermission:output_type -> admin.v1.GroupPermission
	29, // 79: admin.v1.AdminService.ListGroupPermissions:output_type -> admin.v1.GroupPermissionSet
	28, // 80: admin.v1.AdminService.UpdateGroupPermission:output_type -> admin.v1.GroupPermission
	37, // 81: admin.v1.AdminService.DeleteGroupPermission:output_type -> google.protobuf.Empty
	57, // [57:82] is the sub-list for method output_type
	32, // [32:57] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_admin_v1_admin_proto_init() }
func file_admin_v1_admin_proto_init() {
	if File_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_admin_proto_rawDesc), len(file_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_admin_v1_admin_proto = out.File
	file_admin_v1_admin_proto_goTypes = nil
	file_admin_v1_admin_proto_depIdxs = nil
}
