// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: admin/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_ADMIN_UNSPECIFIED                 ErrorReason = 0
	ErrorReason_ADMIN_NOT_FOUND                   ErrorReason = 1
	ErrorReason_ADMIN_INVALID_ARGUMENT            ErrorReason = 2
	ErrorReason_ADMIN_USERNAME_CONFLICT           ErrorReason = 3
	ErrorReason_ROLE_NOT_FOUND                    ErrorReason = 4
	ErrorReason_ROLE_INVALID_ARGUMENT             ErrorReason = 5
	ErrorReason_ROLE_NAME_CONFLICT                ErrorReason = 6
	ErrorReason_ADMIN_ROLE_NOT_FOUND              ErrorReason = 7
	ErrorReason_ADMIN_ROLE_INVALID_ARGUMENT       ErrorReason = 8
	ErrorReason_ADMIN_ROLE_CONFLICT               ErrorReason = 9
	ErrorReason_PERMISSION_NOT_FOUND              ErrorReason = 10
	ErrorReason_PERMISSION_INVALID_ARGUMENT       ErrorReason = 11
	ErrorReason_PERMISSION_HANDLE_CONFLICT        ErrorReason = 12
	ErrorReason_GROUP_PERMISSION_NOT_FOUND        ErrorReason = 13
	ErrorReason_GROUP_PERMISSION_INVALID_ARGUMENT ErrorReason = 14
	ErrorReason_GROUP_PERMISSION_CONFLICT         ErrorReason = 15
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "ADMIN_UNSPECIFIED",
		1:  "ADMIN_NOT_FOUND",
		2:  "ADMIN_INVALID_ARGUMENT",
		3:  "ADMIN_USERNAME_CONFLICT",
		4:  "ROLE_NOT_FOUND",
		5:  "ROLE_INVALID_ARGUMENT",
		6:  "ROLE_NAME_CONFLICT",
		7:  "ADMIN_ROLE_NOT_FOUND",
		8:  "ADMIN_ROLE_INVALID_ARGUMENT",
		9:  "ADMIN_ROLE_CONFLICT",
		10: "PERMISSION_NOT_FOUND",
		11: "PERMISSION_INVALID_ARGUMENT",
		12: "PERMISSION_HANDLE_CONFLICT",
		13: "GROUP_PERMISSION_NOT_FOUND",
		14: "GROUP_PERMISSION_INVALID_ARGUMENT",
		15: "GROUP_PERMISSION_CONFLICT",
	}
	ErrorReason_value = map[string]int32{
		"ADMIN_UNSPECIFIED":                 0,
		"ADMIN_NOT_FOUND":                   1,
		"ADMIN_INVALID_ARGUMENT":            2,
		"ADMIN_USERNAME_CONFLICT":           3,
		"ROLE_NOT_FOUND":                    4,
		"ROLE_INVALID_ARGUMENT":             5,
		"ROLE_NAME_CONFLICT":                6,
		"ADMIN_ROLE_NOT_FOUND":              7,
		"ADMIN_ROLE_INVALID_ARGUMENT":       8,
		"ADMIN_ROLE_CONFLICT":               9,
		"PERMISSION_NOT_FOUND":              10,
		"PERMISSION_INVALID_ARGUMENT":       11,
		"PERMISSION_HANDLE_CONFLICT":        12,
		"GROUP_PERMISSION_NOT_FOUND":        13,
		"GROUP_PERMISSION_INVALID_ARGUMENT": 14,
		"GROUP_PERMISSION_CONFLICT":         15,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_admin_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_admin_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_admin_v1_error_reason_proto protoreflect.FileDescriptor

const file_admin_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1badmin/v1/error_reason.proto\x12\badmin.v1*\xce\x03\n" +
	"\vErrorReason\x12\x15\n" +
	"\x11ADMIN_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fADMIN_NOT_FOUND\x10\x01\x12\x1a\n" +
	"\x16ADMIN_INVALID_ARGUMENT\x10\x02\x12\x1b\n" +
	"\x17ADMIN_USERNAME_CONFLICT\x10\x03\x12\x12\n" +
	"\x0eROLE_NOT_FOUND\x10\x04\x12\x19\n" +
	"\x15ROLE_INVALID_ARGUMENT\x10\x05\x12\x16\n" +
	"\x12ROLE_NAME_CONFLICT\x10\x06\x12\x18\n" +
	"\x14ADMIN_ROLE_NOT_FOUND\x10\a\x12\x1f\n" +
	"\x1bADMIN_ROLE_INVALID_ARGUMENT\x10\b\x12\x17\n" +
	"\x13ADMIN_ROLE_CONFLICT\x10\t\x12\x18\n" +
	"\x14PERMISSION_NOT_FOUND\x10\n" +
	"\x12\x1f\n" +
	"\x1bPERMISSION_INVALID_ARGUMENT\x10\v\x12\x1e\n" +
	"\x1aPERMISSION_HANDLE_CONFLICT\x10\f\x12\x1e\n" +
	"\x1aGROUP_PERMISSION_NOT_FOUND\x10\r\x12%\n" +
	"!GROUP_PERMISSION_INVALID_ARGUMENT\x10\x0e\x12\x1d\n" +
	"\x19GROUP_PERMISSION_CONFLICT\x10\x0fB/\n" +
	"\badmin.v1P\x01Z\x14crow/api/admin/v1;v1\xa2\x02\n" +
	"APIAdminV1b\x06proto3"

var (
	file_admin_v1_error_reason_proto_rawDescOnce sync.Once
	file_admin_v1_error_reason_proto_rawDescData []byte
)

func file_admin_v1_error_reason_proto_rawDescGZIP() []byte {
	file_admin_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_admin_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_v1_error_reason_proto_rawDesc), len(file_admin_v1_error_reason_proto_rawDesc)))
	})
	return file_admin_v1_error_reason_proto_rawDescData
}

var file_admin_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_admin_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: admin.v1.ErrorReason
}
var file_admin_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_admin_v1_error_reason_proto_init() }
func file_admin_v1_error_reason_proto_init() {
	if File_admin_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_v1_error_reason_proto_rawDesc), len(file_admin_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_admin_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_admin_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_admin_v1_error_reason_proto_enumTypes,
	}.Build()
	File_admin_v1_error_reason_proto = out.File
	file_admin_v1_error_reason_proto_goTypes = nil
	file_admin_v1_error_reason_proto_depIdxs = nil
}
