// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: api/login/v1/login.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginRequest is the input for LoginService.Login.
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User account identifier, such as username, email, or phone number.
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// Plaintext password submitted by the client for authentication.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_login_v1_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_login_v1_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_login_v1_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginReply contains the authentication result for a successful login.
type LoginReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Bearer token used to access protected APIs.
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Optional refresh token used to obtain a new access token.
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// Token type returned to the client. Usually "Bearer".
	TokenType string `protobuf:"bytes,3,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	// Access token lifetime in seconds.
	ExpiresIn int64 `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// Authenticated user identifier.
	UserId        int64 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_login_v1_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_login_v1_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_login_v1_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginReply) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginReply) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginReply) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_api_login_v1_login_proto protoreflect.FileDescriptor

const file_api_login_v1_login_proto_rawDesc = "" +
	"\n" +
	"\x18api/login/v1/login.proto\x12\blogin.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\"P\n" +
	"\fLoginRequest\x12\x1e\n" +
	"\aaccount\x18\x01 \x01(\tB\x04\xe2A\x01\x02R\aaccount\x12 \n" +
	"\bpassword\x18\x02 \x01(\tB\x04\xe2A\x01\x02R\bpassword\"\xab\x01\n" +
	"\n" +
	"LoginReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x03 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x03R\texpiresIn\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\x03R\x06userId2[\n" +
	"\fLoginService\x12K\n" +
	"\x05Login\x12\x16.login.v1.LoginRequest\x1a\x14.login.v1.LoginReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/loginB?\n" +
	"\x19io.grpc.examples.login.v1B\n" +
	"LoginProtoP\x01Z\x14crow/api/login/v1;v1b\x06proto3"

var (
	file_api_login_v1_login_proto_rawDescOnce sync.Once
	file_api_login_v1_login_proto_rawDescData []byte
)

func file_api_login_v1_login_proto_rawDescGZIP() []byte {
	file_api_login_v1_login_proto_rawDescOnce.Do(func() {
		file_api_login_v1_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_login_v1_login_proto_rawDesc), len(file_api_login_v1_login_proto_rawDesc)))
	})
	return file_api_login_v1_login_proto_rawDescData
}

var file_api_login_v1_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_login_v1_login_proto_goTypes = []any{
	(*LoginRequest)(nil), // 0: login.v1.LoginRequest
	(*LoginReply)(nil),   // 1: login.v1.LoginReply
}
var file_api_login_v1_login_proto_depIdxs = []int32{
	0, // 0: login.v1.LoginService.Login:input_type -> login.v1.LoginRequest
	1, // 1: login.v1.LoginService.Login:output_type -> login.v1.LoginReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_login_v1_login_proto_init() }
func file_api_login_v1_login_proto_init() {
	if File_api_login_v1_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_login_v1_login_proto_rawDesc), len(file_api_login_v1_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_login_v1_login_proto_goTypes,
		DependencyIndexes: file_api_login_v1_login_proto_depIdxs,
		MessageInfos:      file_api_login_v1_login_proto_msgTypes,
	}.Build()
	File_api_login_v1_login_proto = out.File
	file_api_login_v1_login_proto_goTypes = nil
	file_api_login_v1_login_proto_depIdxs = nil
}
