// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             v7.36.0--rc1
// source: api/login/v1/login.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationLoginServiceLogin = "/login.v1.LoginService/Login"

type LoginServiceHTTPServer interface {
	// Login Login authenticates a user with account credentials and returns tokens
	// for subsequent authenticated requests.
	Login(context.Context, *LoginRequest) (*LoginReply, error)
}

func RegisterLoginServiceHTTPServer(s *http.Server, srv LoginServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/login", _LoginService_Login0_HTTP_Handler(srv))
}

func _LoginService_Login0_HTTP_Handler(srv LoginServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLoginServiceLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginReply)
		return ctx.Result(200, reply)
	}
}

type LoginServiceHTTPClient interface {
	// Login Login authenticates a user with account credentials and returns tokens
	// for subsequent authenticated requests.
	Login(ctx context.Context, req *LoginRequest, opts ...http.CallOption) (rsp *LoginReply, err error)
}

type LoginServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewLoginServiceHTTPClient(client *http.Client) LoginServiceHTTPClient {
	return &LoginServiceHTTPClientImpl{client}
}

// Login Login authenticates a user with account credentials and returns tokens
// for subsequent authenticated requests.
func (c *LoginServiceHTTPClientImpl) Login(ctx context.Context, in *LoginRequest, opts ...http.CallOption) (*LoginReply, error) {
	var out LoginReply
	pattern := "/v1/login"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationLoginServiceLogin),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
