// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cdn/v1/cdn.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CpCode        string                 `protobuf:"bytes,2,opt,name=cp_code,json=cpCode,proto3" json:"cp_code,omitempty"`
	CpName        string                 `protobuf:"bytes,3,opt,name=cp_name,json=cpName,proto3" json:"cp_name,omitempty"`
	Status        uint32                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cp) Reset() {
	*x = Cp{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cp) ProtoMessage() {}

func (x *Cp) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cp.ProtoReflect.Descriptor instead.
func (*Cp) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{0}
}

func (x *Cp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cp) GetCpCode() string {
	if x != nil {
		return x.CpCode
	}
	return ""
}

func (x *Cp) GetCpName() string {
	if x != nil {
		return x.CpName
	}
	return ""
}

func (x *Cp) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Cp) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Cp) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type CpSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cps           []*Cp                  `protobuf:"bytes,1,rep,name=cps,proto3" json:"cps,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpSet) Reset() {
	*x = CpSet{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpSet) ProtoMessage() {}

func (x *CpSet) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpSet.ProtoReflect.Descriptor instead.
func (*CpSet) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{1}
}

func (x *CpSet) GetCps() []*Cp {
	if x != nil {
		return x.Cps
	}
	return nil
}

func (x *CpSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateCpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cp            *Cp                    `protobuf:"bytes,1,opt,name=cp,proto3" json:"cp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCpRequest) Reset() {
	*x = CreateCpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCpRequest) ProtoMessage() {}

func (x *CreateCpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCpRequest.ProtoReflect.Descriptor instead.
func (*CreateCpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCpRequest) GetCp() *Cp {
	if x != nil {
		return x.Cp
	}
	return nil
}

type GetCpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCpRequest) Reset() {
	*x = GetCpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCpRequest) ProtoMessage() {}

func (x *GetCpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCpRequest.ProtoReflect.Descriptor instead.
func (*GetCpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{3}
}

func (x *GetCpRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCpsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCpsRequest) Reset() {
	*x = ListCpsRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCpsRequest) ProtoMessage() {}

func (x *ListCpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCpsRequest.ProtoReflect.Descriptor instead.
func (*ListCpsRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{4}
}

func (x *ListCpsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCpsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCpsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListCpsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type UpdateCpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cp            *Cp                    `protobuf:"bytes,1,opt,name=cp,proto3" json:"cp,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCpRequest) Reset() {
	*x = UpdateCpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCpRequest) ProtoMessage() {}

func (x *UpdateCpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCpRequest.ProtoReflect.Descriptor instead.
func (*UpdateCpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCpRequest) GetCp() *Cp {
	if x != nil {
		return x.Cp
	}
	return nil
}

func (x *UpdateCpRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteCpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCpRequest) Reset() {
	*x = DeleteCpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCpRequest) ProtoMessage() {}

func (x *DeleteCpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCpRequest.ProtoReflect.Descriptor instead.
func (*DeleteCpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCpRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Sp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SpCode        string                 `protobuf:"bytes,2,opt,name=sp_code,json=spCode,proto3" json:"sp_code,omitempty"`
	SpName        string                 `protobuf:"bytes,3,opt,name=sp_name,json=spName,proto3" json:"sp_name,omitempty"`
	SpConfig      string                 `protobuf:"bytes,4,opt,name=sp_config,json=spConfig,proto3" json:"sp_config,omitempty"`
	Status        uint32                 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sp) Reset() {
	*x = Sp{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sp) ProtoMessage() {}

func (x *Sp) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sp.ProtoReflect.Descriptor instead.
func (*Sp) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{7}
}

func (x *Sp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sp) GetSpCode() string {
	if x != nil {
		return x.SpCode
	}
	return ""
}

func (x *Sp) GetSpName() string {
	if x != nil {
		return x.SpName
	}
	return ""
}

func (x *Sp) GetSpConfig() string {
	if x != nil {
		return x.SpConfig
	}
	return ""
}

func (x *Sp) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Sp) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Sp) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type SpSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sps           []*Sp                  `protobuf:"bytes,1,rep,name=sps,proto3" json:"sps,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpSet) Reset() {
	*x = SpSet{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpSet) ProtoMessage() {}

func (x *SpSet) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpSet.ProtoReflect.Descriptor instead.
func (*SpSet) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{8}
}

func (x *SpSet) GetSps() []*Sp {
	if x != nil {
		return x.Sps
	}
	return nil
}

func (x *SpSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateSpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sp            *Sp                    `protobuf:"bytes,1,opt,name=sp,proto3" json:"sp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSpRequest) Reset() {
	*x = CreateSpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSpRequest) ProtoMessage() {}

func (x *CreateSpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSpRequest.ProtoReflect.Descriptor instead.
func (*CreateSpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSpRequest) GetSp() *Sp {
	if x != nil {
		return x.Sp
	}
	return nil
}

type GetSpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpRequest) Reset() {
	*x = GetSpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpRequest) ProtoMessage() {}

func (x *GetSpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpRequest.ProtoReflect.Descriptor instead.
func (*GetSpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{10}
}

func (x *GetSpRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListSpsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSpsRequest) Reset() {
	*x = ListSpsRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSpsRequest) ProtoMessage() {}

func (x *ListSpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSpsRequest.ProtoReflect.Descriptor instead.
func (*ListSpsRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{11}
}

func (x *ListSpsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSpsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListSpsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListSpsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type UpdateSpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sp            *Sp                    `protobuf:"bytes,1,opt,name=sp,proto3" json:"sp,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSpRequest) Reset() {
	*x = UpdateSpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSpRequest) ProtoMessage() {}

func (x *UpdateSpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSpRequest.ProtoReflect.Descriptor instead.
func (*UpdateSpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSpRequest) GetSp() *Sp {
	if x != nil {
		return x.Sp
	}
	return nil
}

func (x *UpdateSpRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteSpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSpRequest) Reset() {
	*x = DeleteSpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSpRequest) ProtoMessage() {}

func (x *DeleteSpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSpRequest.ProtoReflect.Descriptor instead.
func (*DeleteSpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSpRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CpSp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CpId          int64                  `protobuf:"varint,2,opt,name=cp_id,json=cpId,proto3" json:"cp_id,omitempty"`
	SpId          int64                  `protobuf:"varint,3,opt,name=sp_id,json=spId,proto3" json:"sp_id,omitempty"`
	Status        uint32                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpSp) Reset() {
	*x = CpSp{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpSp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpSp) ProtoMessage() {}

func (x *CpSp) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpSp.ProtoReflect.Descriptor instead.
func (*CpSp) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{14}
}

func (x *CpSp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CpSp) GetCpId() int64 {
	if x != nil {
		return x.CpId
	}
	return 0
}

func (x *CpSp) GetSpId() int64 {
	if x != nil {
		return x.SpId
	}
	return 0
}

func (x *CpSp) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CpSp) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *CpSp) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type CpSpSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpSps         []*CpSp                `protobuf:"bytes,1,rep,name=cp_sps,json=cpSps,proto3" json:"cp_sps,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CpSpSet) Reset() {
	*x = CpSpSet{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CpSpSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpSpSet) ProtoMessage() {}

func (x *CpSpSet) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpSpSet.ProtoReflect.Descriptor instead.
func (*CpSpSet) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{15}
}

func (x *CpSpSet) GetCpSps() []*CpSp {
	if x != nil {
		return x.CpSps
	}
	return nil
}

func (x *CpSpSet) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CreateCpSpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpSp          *CpSp                  `protobuf:"bytes,1,opt,name=cp_sp,json=cpSp,proto3" json:"cp_sp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCpSpRequest) Reset() {
	*x = CreateCpSpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCpSpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCpSpRequest) ProtoMessage() {}

func (x *CreateCpSpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCpSpRequest.ProtoReflect.Descriptor instead.
func (*CreateCpSpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{16}
}

func (x *CreateCpSpRequest) GetCpSp() *CpSp {
	if x != nil {
		return x.CpSp
	}
	return nil
}

type GetCpSpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCpSpRequest) Reset() {
	*x = GetCpSpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCpSpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCpSpRequest) ProtoMessage() {}

func (x *GetCpSpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCpSpRequest.ProtoReflect.Descriptor instead.
func (*GetCpSpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{17}
}

func (x *GetCpSpRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCpSpsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string                 `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCpSpsRequest) Reset() {
	*x = ListCpSpsRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCpSpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCpSpsRequest) ProtoMessage() {}

func (x *ListCpSpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCpSpsRequest.ProtoReflect.Descriptor instead.
func (*ListCpSpsRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{18}
}

func (x *ListCpSpsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCpSpsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCpSpsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListCpSpsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type UpdateCpSpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpSp          *CpSp                  `protobuf:"bytes,1,opt,name=cp_sp,json=cpSp,proto3" json:"cp_sp,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCpSpRequest) Reset() {
	*x = UpdateCpSpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCpSpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCpSpRequest) ProtoMessage() {}

func (x *UpdateCpSpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCpSpRequest.ProtoReflect.Descriptor instead.
func (*UpdateCpSpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateCpSpRequest) GetCpSp() *CpSp {
	if x != nil {
		return x.CpSp
	}
	return nil
}

func (x *UpdateCpSpRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteCpSpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCpSpRequest) Reset() {
	*x = DeleteCpSpRequest{}
	mi := &file_cdn_v1_cdn_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCpSpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCpSpRequest) ProtoMessage() {}

func (x *DeleteCpSpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cdn_v1_cdn_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCpSpRequest.ProtoReflect.Descriptor instead.
func (*DeleteCpSpRequest) Descriptor() ([]byte, []int) {
	return file_cdn_v1_cdn_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteCpSpRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_cdn_v1_cdn_proto protoreflect.FileDescriptor

const file_cdn_v1_cdn_proto_rawDesc = "" +
	"\n" +
	"\x10cdn/v1/cdn.proto\x12\x06cdn.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n" +
	"\x02Cp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\acp_code\x18\x02 \x01(\tR\x06cpCode\x12\x17\n" +
	"\acp_name\x18\x03 \x01(\tR\x06cpName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\rR\x06status\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"M\n" +
	"\x05CpSet\x12\x1c\n" +
	"\x03cps\x18\x01 \x03(\v2\n" +
	".cdn.v1.CpR\x03cps\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"2\n" +
	"\x0fCreateCpRequest\x12\x1f\n" +
	"\x02cp\x18\x01 \x01(\v2\n" +
	".cdn.v1.CpB\x03\xe0A\x02R\x02cp\"#\n" +
	"\fGetCpRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x7f\n" +
	"\x0eListCpsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"t\n" +
	"\x0fUpdateCpRequest\x12\x1f\n" +
	"\x02cp\x18\x01 \x01(\v2\n" +
	".cdn.v1.CpB\x03\xe0A\x02R\x02cp\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"&\n" +
	"\x0fDeleteCpRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\xf5\x01\n" +
	"\x02Sp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\asp_code\x18\x02 \x01(\tR\x06spCode\x12\x17\n" +
	"\asp_name\x18\x03 \x01(\tR\x06spName\x12\x1b\n" +
	"\tsp_config\x18\x04 \x01(\tR\bspConfig\x12\x16\n" +
	"\x06status\x18\x05 \x01(\rR\x06status\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"M\n" +
	"\x05SpSet\x12\x1c\n" +
	"\x03sps\x18\x01 \x03(\v2\n" +
	".cdn.v1.SpR\x03sps\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"2\n" +
	"\x0fCreateSpRequest\x12\x1f\n" +
	"\x02sp\x18\x01 \x01(\v2\n" +
	".cdn.v1.SpB\x03\xe0A\x02R\x02sp\"#\n" +
	"\fGetSpRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x7f\n" +
	"\x0eListSpsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"t\n" +
	"\x0fUpdateSpRequest\x12\x1f\n" +
	"\x02sp\x18\x01 \x01(\v2\n" +
	".cdn.v1.SpB\x03\xe0A\x02R\x02sp\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"&\n" +
	"\x0fDeleteSpRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\xd2\x01\n" +
	"\x04CpSp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x13\n" +
	"\x05cp_id\x18\x02 \x01(\x03R\x04cpId\x12\x13\n" +
	"\x05sp_id\x18\x03 \x01(\x03R\x04spId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\rR\x06status\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"V\n" +
	"\aCpSpSet\x12#\n" +
	"\x06cp_sps\x18\x01 \x03(\v2\f.cdn.v1.CpSpR\x05cpSps\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\";\n" +
	"\x11CreateCpSpRequest\x12&\n" +
	"\x05cp_sp\x18\x01 \x01(\v2\f.cdn.v1.CpSpB\x03\xe0A\x02R\x04cpSp\"%\n" +
	"\x0eGetCpSpRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\x81\x01\n" +
	"\x10ListCpSpsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\"}\n" +
	"\x11UpdateCpSpRequest\x12&\n" +
	"\x05cp_sp\x18\x01 \x01(\v2\f.cdn.v1.CpSpB\x03\xe0A\x02R\x04cpSp\x12@\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskB\x03\xe0A\x02R\n" +
	"updateMask\"(\n" +
	"\x11DeleteCpSpRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id2\xfc\x02\n" +
	"\tCpService\x12K\n" +
	"\bCreateCp\x12\x17.cdn.v1.CreateCpRequest\x1a\n" +
	".cdn.v1.Cp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x02cp\"\x0e/v1/cps/create\x12?\n" +
	"\x05GetCp\x12\x14.cdn.v1.GetCpRequest\x1a\n" +
	".cdn.v1.Cp\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/cps/{id}\x12A\n" +
	"\aListCps\x12\x16.cdn.v1.ListCpsRequest\x1a\r.cdn.v1.CpSet\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/v1/cps\x12K\n" +
	"\bUpdateCp\x12\x17.cdn.v1.UpdateCpRequest\x1a\n" +
	".cdn.v1.Cp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x02cp\x1a\x0e/v1/cps/update\x12Q\n" +
	"\bDeleteCp\x12\x17.cdn.v1.DeleteCpRequest\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/v1/cps/{id}2\xfc\x02\n" +
	"\tSpService\x12K\n" +
	"\bCreateSp\x12\x17.cdn.v1.CreateSpRequest\x1a\n" +
	".cdn.v1.Sp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x02sp\"\x0e/v1/sps/create\x12?\n" +
	"\x05GetSp\x12\x14.cdn.v1.GetSpRequest\x1a\n" +
	".cdn.v1.Sp\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/sps/{id}\x12A\n" +
	"\aListSps\x12\x16.cdn.v1.ListSpsRequest\x1a\r.cdn.v1.SpSet\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/v1/sps\x12K\n" +
	"\bUpdateSp\x12\x17.cdn.v1.UpdateSpRequest\x1a\n" +
	".cdn.v1.Sp\"\x1a\x82\xd3\xe4\x93\x02\x14:\x02sp\x1a\x0e/v1/sps/update\x12Q\n" +
	"\bDeleteSp\x12\x17.cdn.v1.DeleteSpRequest\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/v1/sps/{id}2\xaf\x03\n" +
	"\vCpSpService\x12W\n" +
	"\n" +
	"CreateCpSp\x12\x19.cdn.v1.CreateCpSpRequest\x1a\f.cdn.v1.CpSp\" \x82\xd3\xe4\x93\x02\x1a:\x05cp_sp\"\x11/v1/cp-sps/create\x12H\n" +
	"\aGetCpSp\x12\x16.cdn.v1.GetCpSpRequest\x1a\f.cdn.v1.CpSp\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/cp-sps/{id}\x12J\n" +
	"\tListCpSps\x12\x18.cdn.v1.ListCpSpsRequest\x1a\x0f.cdn.v1.CpSpSet\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/cp-sps\x12W\n" +
	"\n" +
	"UpdateCpSp\x12\x19.cdn.v1.UpdateCpSpRequest\x1a\f.cdn.v1.CpSp\" \x82\xd3\xe4\x93\x02\x1a:\x05cp_sp\x1a\x11/v1/cp-sps/update\x12X\n" +
	"\n" +
	"DeleteCpSp\x12\x19.cdn.v1.DeleteCpSpRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/cp-sps/{id}B9\n" +
	"\x17io.grpc.examples.cdn.v1B\bCdnProtoP\x01Z\x12crow/api/cdn/v1;v1b\x06proto3"

var (
	file_cdn_v1_cdn_proto_rawDescOnce sync.Once
	file_cdn_v1_cdn_proto_rawDescData []byte
)

func file_cdn_v1_cdn_proto_rawDescGZIP() []byte {
	file_cdn_v1_cdn_proto_rawDescOnce.Do(func() {
		file_cdn_v1_cdn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cdn_v1_cdn_proto_rawDesc), len(file_cdn_v1_cdn_proto_rawDesc)))
	})
	return file_cdn_v1_cdn_proto_rawDescData
}

var file_cdn_v1_cdn_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_cdn_v1_cdn_proto_goTypes = []any{
	(*Cp)(nil),                    // 0: cdn.v1.Cp
	(*CpSet)(nil),                 // 1: cdn.v1.CpSet
	(*CreateCpRequest)(nil),       // 2: cdn.v1.CreateCpRequest
	(*GetCpRequest)(nil),          // 3: cdn.v1.GetCpRequest
	(*ListCpsRequest)(nil),        // 4: cdn.v1.ListCpsRequest
	(*UpdateCpRequest)(nil),       // 5: cdn.v1.UpdateCpRequest
	(*DeleteCpRequest)(nil),       // 6: cdn.v1.DeleteCpRequest
	(*Sp)(nil),                    // 7: cdn.v1.Sp
	(*SpSet)(nil),                 // 8: cdn.v1.SpSet
	(*CreateSpRequest)(nil),       // 9: cdn.v1.CreateSpRequest
	(*GetSpRequest)(nil),          // 10: cdn.v1.GetSpRequest
	(*ListSpsRequest)(nil),        // 11: cdn.v1.ListSpsRequest
	(*UpdateSpRequest)(nil),       // 12: cdn.v1.UpdateSpRequest
	(*DeleteSpRequest)(nil),       // 13: cdn.v1.DeleteSpRequest
	(*CpSp)(nil),                  // 14: cdn.v1.CpSp
	(*CpSpSet)(nil),               // 15: cdn.v1.CpSpSet
	(*CreateCpSpRequest)(nil),     // 16: cdn.v1.CreateCpSpRequest
	(*GetCpSpRequest)(nil),        // 17: cdn.v1.GetCpSpRequest
	(*ListCpSpsRequest)(nil),      // 18: cdn.v1.ListCpSpsRequest
	(*UpdateCpSpRequest)(nil),     // 19: cdn.v1.UpdateCpSpRequest
	(*DeleteCpSpRequest)(nil),     // 20: cdn.v1.DeleteCpSpRequest
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 22: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 23: google.protobuf.Empty
}
var file_cdn_v1_cdn_proto_depIdxs = []int32{
	21, // 0: cdn.v1.Cp.create_time:type_name -> google.protobuf.Timestamp
	21, // 1: cdn.v1.Cp.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: cdn.v1.CpSet.cps:type_name -> cdn.v1.Cp
	0,  // 3: cdn.v1.CreateCpRequest.cp:type_name -> cdn.v1.Cp
	0,  // 4: cdn.v1.UpdateCpRequest.cp:type_name -> cdn.v1.Cp
	22, // 5: cdn.v1.UpdateCpRequest.update_mask:type_name -> google.protobuf.FieldMask
	21, // 6: cdn.v1.Sp.create_time:type_name -> google.protobuf.Timestamp
	21, // 7: cdn.v1.Sp.update_time:type_name -> google.protobuf.Timestamp
	7,  // 8: cdn.v1.SpSet.sps:type_name -> cdn.v1.Sp
	7,  // 9: cdn.v1.CreateSpRequest.sp:type_name -> cdn.v1.Sp
	7,  // 10: cdn.v1.UpdateSpRequest.sp:type_name -> cdn.v1.Sp
	22, // 11: cdn.v1.UpdateSpRequest.update_mask:type_name -> google.protobuf.FieldMask
	21, // 12: cdn.v1.CpSp.create_time:type_name -> google.protobuf.Timestamp
	21, // 13: cdn.v1.CpSp.update_time:type_name -> google.protobuf.Timestamp
	14, // 14: cdn.v1.CpSpSet.cp_sps:type_name -> cdn.v1.CpSp
	14, // 15: cdn.v1.CreateCpSpRequest.cp_sp:type_name -> cdn.v1.CpSp
	14, // 16: cdn.v1.UpdateCpSpRequest.cp_sp:type_name -> cdn.v1.CpSp
	22, // 17: cdn.v1.UpdateCpSpRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 18: cdn.v1.CpService.CreateCp:input_type -> cdn.v1.CreateCpRequest
	3,  // 19: cdn.v1.CpService.GetCp:input_type -> cdn.v1.GetCpRequest
	4,  // 20: cdn.v1.CpService.ListCps:input_type -> cdn.v1.ListCpsRequest
	5,  // 21: cdn.v1.CpService.UpdateCp:input_type -> cdn.v1.UpdateCpRequest
	6,  // 22: cdn.v1.CpService.DeleteCp:input_type -> cdn.v1.DeleteCpRequest
	9,  // 23: cdn.v1.SpService.CreateSp:input_type -> cdn.v1.CreateSpRequest
	10, // 24: cdn.v1.SpService.GetSp:input_type -> cdn.v1.GetSpRequest
	11, // 25: cdn.v1.SpService.ListSps:input_type -> cdn.v1.ListSpsRequest
	12, // 26: cdn.v1.SpService.UpdateSp:input_type -> cdn.v1.UpdateSpRequest
	13, // 27: cdn.v1.SpService.DeleteSp:input_type -> cdn.v1.DeleteSpRequest
	16, // 28: cdn.v1.CpSpService.CreateCpSp:input_type -> cdn.v1.CreateCpSpRequest
	17, // 29: cdn.v1.CpSpService.GetCpSp:input_type -> cdn.v1.GetCpSpRequest
	18, // 30: cdn.v1.CpSpService.ListCpSps:input_type -> cdn.v1.ListCpSpsRequest
	19, // 31: cdn.v1.CpSpService.UpdateCpSp:input_type -> cdn.v1.UpdateCpSpRequest
	20, // 32: cdn.v1.CpSpService.DeleteCpSp:input_type -> cdn.v1.DeleteCpSpRequest
	0,  // 33: cdn.v1.CpService.CreateCp:output_type -> cdn.v1.Cp
	0,  // 34: cdn.v1.CpService.GetCp:output_type -> cdn.v1.Cp
	1,  // 35: cdn.v1.CpService.ListCps:output_type -> cdn.v1.CpSet
	0,  // 36: cdn.v1.CpService.UpdateCp:output_type -> cdn.v1.Cp
	23, // 37: cdn.v1.CpService.DeleteCp:output_type -> google.protobuf.Empty
	7,  // 38: cdn.v1.SpService.CreateSp:output_type -> cdn.v1.Sp
	7,  // 39: cdn.v1.SpService.GetSp:output_type -> cdn.v1.Sp
	8,  // 40: cdn.v1.SpService.ListSps:output_type -> cdn.v1.SpSet
	7,  // 41: cdn.v1.SpService.UpdateSp:output_type -> cdn.v1.Sp
	23, // 42: cdn.v1.SpService.DeleteSp:output_type -> google.protobuf.Empty
	14, // 43: cdn.v1.CpSpService.CreateCpSp:output_type -> cdn.v1.CpSp
	14, // 44: cdn.v1.CpSpService.GetCpSp:output_type -> cdn.v1.CpSp
	15, // 45: cdn.v1.CpSpService.ListCpSps:output_type -> cdn.v1.CpSpSet
	14, // 46: cdn.v1.CpSpService.UpdateCpSp:output_type -> cdn.v1.CpSp
	23, // 47: cdn.v1.CpSpService.DeleteCpSp:output_type -> google.protobuf.Empty
	33, // [33:48] is the sub-list for method output_type
	18, // [18:33] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_cdn_v1_cdn_proto_init() }
func file_cdn_v1_cdn_proto_init() {
	if File_cdn_v1_cdn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cdn_v1_cdn_proto_rawDesc), len(file_cdn_v1_cdn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_cdn_v1_cdn_proto_goTypes,
		DependencyIndexes: file_cdn_v1_cdn_proto_depIdxs,
		MessageInfos:      file_cdn_v1_cdn_proto_msgTypes,
	}.Build()
	File_cdn_v1_cdn_proto = out.File
	file_cdn_v1_cdn_proto_goTypes = nil
	file_cdn_v1_cdn_proto_depIdxs = nil
}
