// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cdn/v1/cdn.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CpService_CreateCp_FullMethodName = "/cdn.v1.CpService/CreateCp"
	CpService_GetCp_FullMethodName    = "/cdn.v1.CpService/GetCp"
	CpService_ListCps_FullMethodName  = "/cdn.v1.CpService/ListCps"
	CpService_UpdateCp_FullMethodName = "/cdn.v1.CpService/UpdateCp"
	CpService_DeleteCp_FullMethodName = "/cdn.v1.CpService/DeleteCp"
)

// CpServiceClient is the client API for CpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CpServiceClient interface {
	CreateCp(ctx context.Context, in *CreateCpRequest, opts ...grpc.CallOption) (*Cp, error)
	GetCp(ctx context.Context, in *GetCpRequest, opts ...grpc.CallOption) (*Cp, error)
	ListCps(ctx context.Context, in *ListCpsRequest, opts ...grpc.CallOption) (*CpSet, error)
	UpdateCp(ctx context.Context, in *UpdateCpRequest, opts ...grpc.CallOption) (*Cp, error)
	DeleteCp(ctx context.Context, in *DeleteCpRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type cpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCpServiceClient(cc grpc.ClientConnInterface) CpServiceClient {
	return &cpServiceClient{cc}
}

func (c *cpServiceClient) CreateCp(ctx context.Context, in *CreateCpRequest, opts ...grpc.CallOption) (*Cp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cp)
	err := c.cc.Invoke(ctx, CpService_CreateCp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpServiceClient) GetCp(ctx context.Context, in *GetCpRequest, opts ...grpc.CallOption) (*Cp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cp)
	err := c.cc.Invoke(ctx, CpService_GetCp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpServiceClient) ListCps(ctx context.Context, in *ListCpsRequest, opts ...grpc.CallOption) (*CpSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpSet)
	err := c.cc.Invoke(ctx, CpService_ListCps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpServiceClient) UpdateCp(ctx context.Context, in *UpdateCpRequest, opts ...grpc.CallOption) (*Cp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Cp)
	err := c.cc.Invoke(ctx, CpService_UpdateCp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpServiceClient) DeleteCp(ctx context.Context, in *DeleteCpRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CpService_DeleteCp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CpServiceServer is the server API for CpService service.
// All implementations must embed UnimplementedCpServiceServer
// for forward compatibility.
type CpServiceServer interface {
	CreateCp(context.Context, *CreateCpRequest) (*Cp, error)
	GetCp(context.Context, *GetCpRequest) (*Cp, error)
	ListCps(context.Context, *ListCpsRequest) (*CpSet, error)
	UpdateCp(context.Context, *UpdateCpRequest) (*Cp, error)
	DeleteCp(context.Context, *DeleteCpRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCpServiceServer()
}

// UnimplementedCpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCpServiceServer struct{}

func (UnimplementedCpServiceServer) CreateCp(context.Context, *CreateCpRequest) (*Cp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCp not implemented")
}
func (UnimplementedCpServiceServer) GetCp(context.Context, *GetCpRequest) (*Cp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCp not implemented")
}
func (UnimplementedCpServiceServer) ListCps(context.Context, *ListCpsRequest) (*CpSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCps not implemented")
}
func (UnimplementedCpServiceServer) UpdateCp(context.Context, *UpdateCpRequest) (*Cp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCp not implemented")
}
func (UnimplementedCpServiceServer) DeleteCp(context.Context, *DeleteCpRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCp not implemented")
}
func (UnimplementedCpServiceServer) mustEmbedUnimplementedCpServiceServer() {}
func (UnimplementedCpServiceServer) testEmbeddedByValue()                   {}

// UnsafeCpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CpServiceServer will
// result in compilation errors.
type UnsafeCpServiceServer interface {
	mustEmbedUnimplementedCpServiceServer()
}

func RegisterCpServiceServer(s grpc.ServiceRegistrar, srv CpServiceServer) {
	// If the following call panics, it indicates UnimplementedCpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CpService_ServiceDesc, srv)
}

func _CpService_CreateCp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpServiceServer).CreateCp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpService_CreateCp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpServiceServer).CreateCp(ctx, req.(*CreateCpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpService_GetCp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpServiceServer).GetCp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpService_GetCp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpServiceServer).GetCp(ctx, req.(*GetCpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpService_ListCps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpServiceServer).ListCps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpService_ListCps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpServiceServer).ListCps(ctx, req.(*ListCpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpService_UpdateCp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpServiceServer).UpdateCp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpService_UpdateCp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpServiceServer).UpdateCp(ctx, req.(*UpdateCpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpService_DeleteCp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpServiceServer).DeleteCp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpService_DeleteCp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpServiceServer).DeleteCp(ctx, req.(*DeleteCpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CpService_ServiceDesc is the grpc.ServiceDesc for CpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdn.v1.CpService",
	HandlerType: (*CpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCp",
			Handler:    _CpService_CreateCp_Handler,
		},
		{
			MethodName: "GetCp",
			Handler:    _CpService_GetCp_Handler,
		},
		{
			MethodName: "ListCps",
			Handler:    _CpService_ListCps_Handler,
		},
		{
			MethodName: "UpdateCp",
			Handler:    _CpService_UpdateCp_Handler,
		},
		{
			MethodName: "DeleteCp",
			Handler:    _CpService_DeleteCp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdn/v1/cdn.proto",
}

const (
	SpService_CreateSp_FullMethodName = "/cdn.v1.SpService/CreateSp"
	SpService_GetSp_FullMethodName    = "/cdn.v1.SpService/GetSp"
	SpService_ListSps_FullMethodName  = "/cdn.v1.SpService/ListSps"
	SpService_UpdateSp_FullMethodName = "/cdn.v1.SpService/UpdateSp"
	SpService_DeleteSp_FullMethodName = "/cdn.v1.SpService/DeleteSp"
)

// SpServiceClient is the client API for SpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpServiceClient interface {
	CreateSp(ctx context.Context, in *CreateSpRequest, opts ...grpc.CallOption) (*Sp, error)
	GetSp(ctx context.Context, in *GetSpRequest, opts ...grpc.CallOption) (*Sp, error)
	ListSps(ctx context.Context, in *ListSpsRequest, opts ...grpc.CallOption) (*SpSet, error)
	UpdateSp(ctx context.Context, in *UpdateSpRequest, opts ...grpc.CallOption) (*Sp, error)
	DeleteSp(ctx context.Context, in *DeleteSpRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type spServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpServiceClient(cc grpc.ClientConnInterface) SpServiceClient {
	return &spServiceClient{cc}
}

func (c *spServiceClient) CreateSp(ctx context.Context, in *CreateSpRequest, opts ...grpc.CallOption) (*Sp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Sp)
	err := c.cc.Invoke(ctx, SpService_CreateSp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spServiceClient) GetSp(ctx context.Context, in *GetSpRequest, opts ...grpc.CallOption) (*Sp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Sp)
	err := c.cc.Invoke(ctx, SpService_GetSp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spServiceClient) ListSps(ctx context.Context, in *ListSpsRequest, opts ...grpc.CallOption) (*SpSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SpSet)
	err := c.cc.Invoke(ctx, SpService_ListSps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spServiceClient) UpdateSp(ctx context.Context, in *UpdateSpRequest, opts ...grpc.CallOption) (*Sp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Sp)
	err := c.cc.Invoke(ctx, SpService_UpdateSp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spServiceClient) DeleteSp(ctx context.Context, in *DeleteSpRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SpService_DeleteSp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpServiceServer is the server API for SpService service.
// All implementations must embed UnimplementedSpServiceServer
// for forward compatibility.
type SpServiceServer interface {
	CreateSp(context.Context, *CreateSpRequest) (*Sp, error)
	GetSp(context.Context, *GetSpRequest) (*Sp, error)
	ListSps(context.Context, *ListSpsRequest) (*SpSet, error)
	UpdateSp(context.Context, *UpdateSpRequest) (*Sp, error)
	DeleteSp(context.Context, *DeleteSpRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSpServiceServer()
}

// UnimplementedSpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpServiceServer struct{}

func (UnimplementedSpServiceServer) CreateSp(context.Context, *CreateSpRequest) (*Sp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSp not implemented")
}
func (UnimplementedSpServiceServer) GetSp(context.Context, *GetSpRequest) (*Sp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSp not implemented")
}
func (UnimplementedSpServiceServer) ListSps(context.Context, *ListSpsRequest) (*SpSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSps not implemented")
}
func (UnimplementedSpServiceServer) UpdateSp(context.Context, *UpdateSpRequest) (*Sp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSp not implemented")
}
func (UnimplementedSpServiceServer) DeleteSp(context.Context, *DeleteSpRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSp not implemented")
}
func (UnimplementedSpServiceServer) mustEmbedUnimplementedSpServiceServer() {}
func (UnimplementedSpServiceServer) testEmbeddedByValue()                   {}

// UnsafeSpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpServiceServer will
// result in compilation errors.
type UnsafeSpServiceServer interface {
	mustEmbedUnimplementedSpServiceServer()
}

func RegisterSpServiceServer(s grpc.ServiceRegistrar, srv SpServiceServer) {
	// If the following call panics, it indicates UnimplementedSpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpService_ServiceDesc, srv)
}

func _SpService_CreateSp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpServiceServer).CreateSp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpService_CreateSp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpServiceServer).CreateSp(ctx, req.(*CreateSpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpService_GetSp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpServiceServer).GetSp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpService_GetSp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpServiceServer).GetSp(ctx, req.(*GetSpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpService_ListSps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpServiceServer).ListSps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpService_ListSps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpServiceServer).ListSps(ctx, req.(*ListSpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpService_UpdateSp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpServiceServer).UpdateSp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpService_UpdateSp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpServiceServer).UpdateSp(ctx, req.(*UpdateSpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpService_DeleteSp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpServiceServer).DeleteSp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpService_DeleteSp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpServiceServer).DeleteSp(ctx, req.(*DeleteSpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpService_ServiceDesc is the grpc.ServiceDesc for SpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdn.v1.SpService",
	HandlerType: (*SpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSp",
			Handler:    _SpService_CreateSp_Handler,
		},
		{
			MethodName: "GetSp",
			Handler:    _SpService_GetSp_Handler,
		},
		{
			MethodName: "ListSps",
			Handler:    _SpService_ListSps_Handler,
		},
		{
			MethodName: "UpdateSp",
			Handler:    _SpService_UpdateSp_Handler,
		},
		{
			MethodName: "DeleteSp",
			Handler:    _SpService_DeleteSp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdn/v1/cdn.proto",
}

const (
	CpSpService_CreateCpSp_FullMethodName = "/cdn.v1.CpSpService/CreateCpSp"
	CpSpService_GetCpSp_FullMethodName    = "/cdn.v1.CpSpService/GetCpSp"
	CpSpService_ListCpSps_FullMethodName  = "/cdn.v1.CpSpService/ListCpSps"
	CpSpService_UpdateCpSp_FullMethodName = "/cdn.v1.CpSpService/UpdateCpSp"
	CpSpService_DeleteCpSp_FullMethodName = "/cdn.v1.CpSpService/DeleteCpSp"
)

// CpSpServiceClient is the client API for CpSpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CpSpServiceClient interface {
	CreateCpSp(ctx context.Context, in *CreateCpSpRequest, opts ...grpc.CallOption) (*CpSp, error)
	GetCpSp(ctx context.Context, in *GetCpSpRequest, opts ...grpc.CallOption) (*CpSp, error)
	ListCpSps(ctx context.Context, in *ListCpSpsRequest, opts ...grpc.CallOption) (*CpSpSet, error)
	UpdateCpSp(ctx context.Context, in *UpdateCpSpRequest, opts ...grpc.CallOption) (*CpSp, error)
	DeleteCpSp(ctx context.Context, in *DeleteCpSpRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type cpSpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCpSpServiceClient(cc grpc.ClientConnInterface) CpSpServiceClient {
	return &cpSpServiceClient{cc}
}

func (c *cpSpServiceClient) CreateCpSp(ctx context.Context, in *CreateCpSpRequest, opts ...grpc.CallOption) (*CpSp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpSp)
	err := c.cc.Invoke(ctx, CpSpService_CreateCpSp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpSpServiceClient) GetCpSp(ctx context.Context, in *GetCpSpRequest, opts ...grpc.CallOption) (*CpSp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpSp)
	err := c.cc.Invoke(ctx, CpSpService_GetCpSp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpSpServiceClient) ListCpSps(ctx context.Context, in *ListCpSpsRequest, opts ...grpc.CallOption) (*CpSpSet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpSpSet)
	err := c.cc.Invoke(ctx, CpSpService_ListCpSps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpSpServiceClient) UpdateCpSp(ctx context.Context, in *UpdateCpSpRequest, opts ...grpc.CallOption) (*CpSp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CpSp)
	err := c.cc.Invoke(ctx, CpSpService_UpdateCpSp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cpSpServiceClient) DeleteCpSp(ctx context.Context, in *DeleteCpSpRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CpSpService_DeleteCpSp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CpSpServiceServer is the server API for CpSpService service.
// All implementations must embed UnimplementedCpSpServiceServer
// for forward compatibility.
type CpSpServiceServer interface {
	CreateCpSp(context.Context, *CreateCpSpRequest) (*CpSp, error)
	GetCpSp(context.Context, *GetCpSpRequest) (*CpSp, error)
	ListCpSps(context.Context, *ListCpSpsRequest) (*CpSpSet, error)
	UpdateCpSp(context.Context, *UpdateCpSpRequest) (*CpSp, error)
	DeleteCpSp(context.Context, *DeleteCpSpRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCpSpServiceServer()
}

// UnimplementedCpSpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCpSpServiceServer struct{}

func (UnimplementedCpSpServiceServer) CreateCpSp(context.Context, *CreateCpSpRequest) (*CpSp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCpSp not implemented")
}
func (UnimplementedCpSpServiceServer) GetCpSp(context.Context, *GetCpSpRequest) (*CpSp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCpSp not implemented")
}
func (UnimplementedCpSpServiceServer) ListCpSps(context.Context, *ListCpSpsRequest) (*CpSpSet, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCpSps not implemented")
}
func (UnimplementedCpSpServiceServer) UpdateCpSp(context.Context, *UpdateCpSpRequest) (*CpSp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCpSp not implemented")
}
func (UnimplementedCpSpServiceServer) DeleteCpSp(context.Context, *DeleteCpSpRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCpSp not implemented")
}
func (UnimplementedCpSpServiceServer) mustEmbedUnimplementedCpSpServiceServer() {}
func (UnimplementedCpSpServiceServer) testEmbeddedByValue()                     {}

// UnsafeCpSpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CpSpServiceServer will
// result in compilation errors.
type UnsafeCpSpServiceServer interface {
	mustEmbedUnimplementedCpSpServiceServer()
}

func RegisterCpSpServiceServer(s grpc.ServiceRegistrar, srv CpSpServiceServer) {
	// If the following call panics, it indicates UnimplementedCpSpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CpSpService_ServiceDesc, srv)
}

func _CpSpService_CreateCpSp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCpSpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpSpServiceServer).CreateCpSp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpSpService_CreateCpSp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpSpServiceServer).CreateCpSp(ctx, req.(*CreateCpSpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpSpService_GetCpSp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCpSpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpSpServiceServer).GetCpSp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpSpService_GetCpSp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpSpServiceServer).GetCpSp(ctx, req.(*GetCpSpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpSpService_ListCpSps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCpSpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpSpServiceServer).ListCpSps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpSpService_ListCpSps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpSpServiceServer).ListCpSps(ctx, req.(*ListCpSpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpSpService_UpdateCpSp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCpSpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpSpServiceServer).UpdateCpSp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpSpService_UpdateCpSp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpSpServiceServer).UpdateCpSp(ctx, req.(*UpdateCpSpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CpSpService_DeleteCpSp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCpSpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CpSpServiceServer).DeleteCpSp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CpSpService_DeleteCpSp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CpSpServiceServer).DeleteCpSp(ctx, req.(*DeleteCpSpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CpSpService_ServiceDesc is the grpc.ServiceDesc for CpSpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CpSpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cdn.v1.CpSpService",
	HandlerType: (*CpSpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCpSp",
			Handler:    _CpSpService_CreateCpSp_Handler,
		},
		{
			MethodName: "GetCpSp",
			Handler:    _CpSpService_GetCpSp_Handler,
		},
		{
			MethodName: "ListCpSps",
			Handler:    _CpSpService_ListCpSps_Handler,
		},
		{
			MethodName: "UpdateCpSp",
			Handler:    _CpSpService_UpdateCpSp_Handler,
		},
		{
			MethodName: "DeleteCpSp",
			Handler:    _CpSpService_DeleteCpSp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cdn/v1/cdn.proto",
}
