// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: cdn/v1/cdn.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationCpServiceCreateCp = "/cdn.v1.CpService/CreateCp"
const OperationCpServiceDeleteCp = "/cdn.v1.CpService/DeleteCp"
const OperationCpServiceGetCp = "/cdn.v1.CpService/GetCp"
const OperationCpServiceListCps = "/cdn.v1.CpService/ListCps"
const OperationCpServiceUpdateCp = "/cdn.v1.CpService/UpdateCp"

type CpServiceHTTPServer interface {
	CreateCp(context.Context, *CreateCpRequest) (*Cp, error)
	DeleteCp(context.Context, *DeleteCpRequest) (*emptypb.Empty, error)
	GetCp(context.Context, *GetCpRequest) (*Cp, error)
	ListCps(context.Context, *ListCpsRequest) (*CpSet, error)
	UpdateCp(context.Context, *UpdateCpRequest) (*Cp, error)
}

func RegisterCpServiceHTTPServer(s *http.Server, srv CpServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/cps/create", _CpService_CreateCp0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/cps/{id}", _CpService_GetCp0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/cps", _CpService_ListCps0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/cps/update", _CpService_UpdateCp0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/cps/{id}", _CpService_DeleteCp0_HTTP_Handler(srv))
}

func _CpService_CreateCp0_HTTP_Handler(srv CpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCpRequest
		if err := ctx.Bind(&in.Cp); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCpServiceCreateCp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCp(ctx, req.(*CreateCpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Cp)
		return ctx.Result(200, reply)
	}
}

func _CpService_GetCp0_HTTP_Handler(srv CpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCpRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCpServiceGetCp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCp(ctx, req.(*GetCpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Cp)
		return ctx.Result(200, reply)
	}
}

func _CpService_ListCps0_HTTP_Handler(srv CpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCpsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCpServiceListCps)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCps(ctx, req.(*ListCpsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CpSet)
		return ctx.Result(200, reply)
	}
}

func _CpService_UpdateCp0_HTTP_Handler(srv CpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCpRequest
		if err := ctx.Bind(&in.Cp); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCpServiceUpdateCp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCp(ctx, req.(*UpdateCpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Cp)
		return ctx.Result(200, reply)
	}
}

func _CpService_DeleteCp0_HTTP_Handler(srv CpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCpRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCpServiceDeleteCp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCp(ctx, req.(*DeleteCpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type CpServiceHTTPClient interface {
	CreateCp(ctx context.Context, req *CreateCpRequest, opts ...http.CallOption) (rsp *Cp, err error)
	DeleteCp(ctx context.Context, req *DeleteCpRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetCp(ctx context.Context, req *GetCpRequest, opts ...http.CallOption) (rsp *Cp, err error)
	ListCps(ctx context.Context, req *ListCpsRequest, opts ...http.CallOption) (rsp *CpSet, err error)
	UpdateCp(ctx context.Context, req *UpdateCpRequest, opts ...http.CallOption) (rsp *Cp, err error)
}

type CpServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCpServiceHTTPClient(client *http.Client) CpServiceHTTPClient {
	return &CpServiceHTTPClientImpl{client}
}

func (c *CpServiceHTTPClientImpl) CreateCp(ctx context.Context, in *CreateCpRequest, opts ...http.CallOption) (*Cp, error) {
	var out Cp
	pattern := "/v1/cps/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("cp"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCpServiceCreateCp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Cp, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CpServiceHTTPClientImpl) DeleteCp(ctx context.Context, in *DeleteCpRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/cps/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCpServiceDeleteCp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CpServiceHTTPClientImpl) GetCp(ctx context.Context, in *GetCpRequest, opts ...http.CallOption) (*Cp, error) {
	var out Cp
	pattern := "/v1/cps/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCpServiceGetCp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CpServiceHTTPClientImpl) ListCps(ctx context.Context, in *ListCpsRequest, opts ...http.CallOption) (*CpSet, error) {
	var out CpSet
	pattern := "/v1/cps"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCpServiceListCps),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CpServiceHTTPClientImpl) UpdateCp(ctx context.Context, in *UpdateCpRequest, opts ...http.CallOption) (*Cp, error) {
	var out Cp
	pattern := "/v1/cps/update"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("cp"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCpServiceUpdateCp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in.Cp, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationSpServiceCreateSp = "/cdn.v1.SpService/CreateSp"
const OperationSpServiceDeleteSp = "/cdn.v1.SpService/DeleteSp"
const OperationSpServiceGetSp = "/cdn.v1.SpService/GetSp"
const OperationSpServiceListSps = "/cdn.v1.SpService/ListSps"
const OperationSpServiceUpdateSp = "/cdn.v1.SpService/UpdateSp"

type SpServiceHTTPServer interface {
	CreateSp(context.Context, *CreateSpRequest) (*Sp, error)
	DeleteSp(context.Context, *DeleteSpRequest) (*emptypb.Empty, error)
	GetSp(context.Context, *GetSpRequest) (*Sp, error)
	ListSps(context.Context, *ListSpsRequest) (*SpSet, error)
	UpdateSp(context.Context, *UpdateSpRequest) (*Sp, error)
}

func RegisterSpServiceHTTPServer(s *http.Server, srv SpServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/sps/create", _SpService_CreateSp0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sps/{id}", _SpService_GetSp0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/sps", _SpService_ListSps0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/sps/update", _SpService_UpdateSp0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/sps/{id}", _SpService_DeleteSp0_HTTP_Handler(srv))
}

func _SpService_CreateSp0_HTTP_Handler(srv SpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSpRequest
		if err := ctx.Bind(&in.Sp); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpServiceCreateSp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSp(ctx, req.(*CreateSpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Sp)
		return ctx.Result(200, reply)
	}
}

func _SpService_GetSp0_HTTP_Handler(srv SpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSpRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpServiceGetSp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSp(ctx, req.(*GetSpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Sp)
		return ctx.Result(200, reply)
	}
}

func _SpService_ListSps0_HTTP_Handler(srv SpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSpsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpServiceListSps)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSps(ctx, req.(*ListSpsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SpSet)
		return ctx.Result(200, reply)
	}
}

func _SpService_UpdateSp0_HTTP_Handler(srv SpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSpRequest
		if err := ctx.Bind(&in.Sp); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpServiceUpdateSp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSp(ctx, req.(*UpdateSpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Sp)
		return ctx.Result(200, reply)
	}
}

func _SpService_DeleteSp0_HTTP_Handler(srv SpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSpRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSpServiceDeleteSp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSp(ctx, req.(*DeleteSpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type SpServiceHTTPClient interface {
	CreateSp(ctx context.Context, req *CreateSpRequest, opts ...http.CallOption) (rsp *Sp, err error)
	DeleteSp(ctx context.Context, req *DeleteSpRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetSp(ctx context.Context, req *GetSpRequest, opts ...http.CallOption) (rsp *Sp, err error)
	ListSps(ctx context.Context, req *ListSpsRequest, opts ...http.CallOption) (rsp *SpSet, err error)
	UpdateSp(ctx context.Context, req *UpdateSpRequest, opts ...http.CallOption) (rsp *Sp, err error)
}

type SpServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSpServiceHTTPClient(client *http.Client) SpServiceHTTPClient {
	return &SpServiceHTTPClientImpl{client}
}

func (c *SpServiceHTTPClientImpl) CreateSp(ctx context.Context, in *CreateSpRequest, opts ...http.CallOption) (*Sp, error) {
	var out Sp
	pattern := "/v1/sps/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("sp"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSpServiceCreateSp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Sp, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SpServiceHTTPClientImpl) DeleteSp(ctx context.Context, in *DeleteSpRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/sps/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSpServiceDeleteSp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SpServiceHTTPClientImpl) GetSp(ctx context.Context, in *GetSpRequest, opts ...http.CallOption) (*Sp, error) {
	var out Sp
	pattern := "/v1/sps/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSpServiceGetSp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SpServiceHTTPClientImpl) ListSps(ctx context.Context, in *ListSpsRequest, opts ...http.CallOption) (*SpSet, error) {
	var out SpSet
	pattern := "/v1/sps"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSpServiceListSps),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *SpServiceHTTPClientImpl) UpdateSp(ctx context.Context, in *UpdateSpRequest, opts ...http.CallOption) (*Sp, error) {
	var out Sp
	pattern := "/v1/sps/update"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("sp"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSpServiceUpdateSp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in.Sp, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

const OperationCpSpServiceCreateCpSp = "/cdn.v1.CpSpService/CreateCpSp"
const OperationCpSpServiceDeleteCpSp = "/cdn.v1.CpSpService/DeleteCpSp"
const OperationCpSpServiceGetCpSp = "/cdn.v1.CpSpService/GetCpSp"
const OperationCpSpServiceListCpSps = "/cdn.v1.CpSpService/ListCpSps"
const OperationCpSpServiceUpdateCpSp = "/cdn.v1.CpSpService/UpdateCpSp"

type CpSpServiceHTTPServer interface {
	CreateCpSp(context.Context, *CreateCpSpRequest) (*CpSp, error)
	DeleteCpSp(context.Context, *DeleteCpSpRequest) (*emptypb.Empty, error)
	GetCpSp(context.Context, *GetCpSpRequest) (*CpSp, error)
	ListCpSps(context.Context, *ListCpSpsRequest) (*CpSpSet, error)
	UpdateCpSp(context.Context, *UpdateCpSpRequest) (*CpSp, error)
}

func RegisterCpSpServiceHTTPServer(s *http.Server, srv CpSpServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/cp-sps/create", _CpSpService_CreateCpSp0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/cp-sps/{id}", _CpSpService_GetCpSp0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/cp-sps", _CpSpService_ListCpSps0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/cp-sps/update", _CpSpService_UpdateCpSp0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/cp-sps/{id}", _CpSpService_DeleteCpSp0_HTTP_Handler(srv))
}

func _CpSpService_CreateCpSp0_HTTP_Handler(srv CpSpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCpSpRequest
		if err := ctx.Bind(&in.CpSp); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCpSpServiceCreateCpSp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCpSp(ctx, req.(*CreateCpSpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CpSp)
		return ctx.Result(200, reply)
	}
}

func _CpSpService_GetCpSp0_HTTP_Handler(srv CpSpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCpSpRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCpSpServiceGetCpSp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCpSp(ctx, req.(*GetCpSpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CpSp)
		return ctx.Result(200, reply)
	}
}

func _CpSpService_ListCpSps0_HTTP_Handler(srv CpSpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCpSpsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCpSpServiceListCpSps)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCpSps(ctx, req.(*ListCpSpsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CpSpSet)
		return ctx.Result(200, reply)
	}
}

func _CpSpService_UpdateCpSp0_HTTP_Handler(srv CpSpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCpSpRequest
		if err := ctx.Bind(&in.CpSp); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCpSpServiceUpdateCpSp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCpSp(ctx, req.(*UpdateCpSpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CpSp)
		return ctx.Result(200, reply)
	}
}

func _CpSpService_DeleteCpSp0_HTTP_Handler(srv CpSpServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCpSpRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCpSpServiceDeleteCpSp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCpSp(ctx, req.(*DeleteCpSpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type CpSpServiceHTTPClient interface {
	CreateCpSp(ctx context.Context, req *CreateCpSpRequest, opts ...http.CallOption) (rsp *CpSp, err error)
	DeleteCpSp(ctx context.Context, req *DeleteCpSpRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetCpSp(ctx context.Context, req *GetCpSpRequest, opts ...http.CallOption) (rsp *CpSp, err error)
	ListCpSps(ctx context.Context, req *ListCpSpsRequest, opts ...http.CallOption) (rsp *CpSpSet, err error)
	UpdateCpSp(ctx context.Context, req *UpdateCpSpRequest, opts ...http.CallOption) (rsp *CpSp, err error)
}

type CpSpServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewCpSpServiceHTTPClient(client *http.Client) CpSpServiceHTTPClient {
	return &CpSpServiceHTTPClientImpl{client}
}

func (c *CpSpServiceHTTPClientImpl) CreateCpSp(ctx context.Context, in *CreateCpSpRequest, opts ...http.CallOption) (*CpSp, error) {
	var out CpSp
	pattern := "/v1/cp-sps/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("cpSp"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCpSpServiceCreateCpSp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.CpSp, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CpSpServiceHTTPClientImpl) DeleteCpSp(ctx context.Context, in *DeleteCpSpRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/cp-sps/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCpSpServiceDeleteCpSp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CpSpServiceHTTPClientImpl) GetCpSp(ctx context.Context, in *GetCpSpRequest, opts ...http.CallOption) (*CpSp, error) {
	var out CpSp
	pattern := "/v1/cp-sps/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCpSpServiceGetCpSp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CpSpServiceHTTPClientImpl) ListCpSps(ctx context.Context, in *ListCpSpsRequest, opts ...http.CallOption) (*CpSpSet, error) {
	var out CpSpSet
	pattern := "/v1/cp-sps"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationCpSpServiceListCpSps),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *CpSpServiceHTTPClientImpl) UpdateCpSp(ctx context.Context, in *UpdateCpSpRequest, opts ...http.CallOption) (*CpSp, error) {
	var out CpSp
	pattern := "/v1/cp-sps/update"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("cpSp"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationCpSpServiceUpdateCpSp),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in.CpSp, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
