// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: api/cdn/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_CP_UNSPECIFIED         ErrorReason = 0
	ErrorReason_CP_NOT_FOUND           ErrorReason = 1
	ErrorReason_CP_INVALID_ARGUMENT    ErrorReason = 2
	ErrorReason_CP_CODE_CONFLICT       ErrorReason = 3
	ErrorReason_SP_NOT_FOUND           ErrorReason = 4
	ErrorReason_SP_INVALID_ARGUMENT    ErrorReason = 5
	ErrorReason_SP_CODE_CONFLICT       ErrorReason = 6
	ErrorReason_CP_SP_NOT_FOUND        ErrorReason = 7
	ErrorReason_CP_SP_INVALID_ARGUMENT ErrorReason = 8
	ErrorReason_CP_SP_CONFLICT         ErrorReason = 9
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "CP_UNSPECIFIED",
		1: "CP_NOT_FOUND",
		2: "CP_INVALID_ARGUMENT",
		3: "CP_CODE_CONFLICT",
		4: "SP_NOT_FOUND",
		5: "SP_INVALID_ARGUMENT",
		6: "SP_CODE_CONFLICT",
		7: "CP_SP_NOT_FOUND",
		8: "CP_SP_INVALID_ARGUMENT",
		9: "CP_SP_CONFLICT",
	}
	ErrorReason_value = map[string]int32{
		"CP_UNSPECIFIED":         0,
		"CP_NOT_FOUND":           1,
		"CP_INVALID_ARGUMENT":    2,
		"CP_CODE_CONFLICT":       3,
		"SP_NOT_FOUND":           4,
		"SP_INVALID_ARGUMENT":    5,
		"SP_CODE_CONFLICT":       6,
		"CP_SP_NOT_FOUND":        7,
		"CP_SP_INVALID_ARGUMENT": 8,
		"CP_SP_CONFLICT":         9,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_cdn_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_cdn_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_cdn_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_api_cdn_v1_error_reason_proto protoreflect.FileDescriptor

const file_api_cdn_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/cdn/v1/error_reason.proto\x12\x06cdn.v1*\xe8\x01\n" +
	"\vErrorReason\x12\x12\n" +
	"\x0eCP_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCP_NOT_FOUND\x10\x01\x12\x17\n" +
	"\x13CP_INVALID_ARGUMENT\x10\x02\x12\x14\n" +
	"\x10CP_CODE_CONFLICT\x10\x03\x12\x10\n" +
	"\fSP_NOT_FOUND\x10\x04\x12\x17\n" +
	"\x13SP_INVALID_ARGUMENT\x10\x05\x12\x14\n" +
	"\x10SP_CODE_CONFLICT\x10\x06\x12\x13\n" +
	"\x0fCP_SP_NOT_FOUND\x10\a\x12\x1a\n" +
	"\x16CP_SP_INVALID_ARGUMENT\x10\b\x12\x12\n" +
	"\x0eCP_SP_CONFLICT\x10\tB)\n" +
	"\x06cdn.v1P\x01Z\x12crow/api/cdn/v1;v1\xa2\x02\bAPICdnV1b\x06proto3"

var (
	file_api_cdn_v1_error_reason_proto_rawDescOnce sync.Once
	file_api_cdn_v1_error_reason_proto_rawDescData []byte
)

func file_api_cdn_v1_error_reason_proto_rawDescGZIP() []byte {
	file_api_cdn_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_api_cdn_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cdn_v1_error_reason_proto_rawDesc), len(file_api_cdn_v1_error_reason_proto_rawDesc)))
	})
	return file_api_cdn_v1_error_reason_proto_rawDescData
}

var file_api_cdn_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_cdn_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: cdn.v1.ErrorReason
}
var file_api_cdn_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_cdn_v1_error_reason_proto_init() }
func file_api_cdn_v1_error_reason_proto_init() {
	if File_api_cdn_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cdn_v1_error_reason_proto_rawDesc), len(file_api_cdn_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_cdn_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_api_cdn_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_api_cdn_v1_error_reason_proto_enumTypes,
	}.Build()
	File_api_cdn_v1_error_reason_proto = out.File
	file_api_cdn_v1_error_reason_proto_goTypes = nil
	file_api_cdn_v1_error_reason_proto_depIdxs = nil
}
