// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"crow/internal/biz"
	"crow/internal/conf"
	"crow/internal/data"
	"crow/internal/server"
	"crow/internal/service"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	todoRepo := data.NewTodoRepo(dataData)
	todoUsecase := biz.NewTodoUsecase(todoRepo)
	todoService := service.NewTodoService(todoUsecase)
	loginRepo := data.NewLoginRepo(dataData)
	tokenGenerator := biz.NewLoginTokenGenerator(auth)
	loginUsecase := biz.NewLoginUsecase(loginRepo, tokenGenerator)
	adminOperationLogRepo := data.NewAdminOperationLogRepo(dataData)
	adminOperationLogUsecase := biz.NewAdminOperationLogUsecase(adminOperationLogRepo)
	loginService := service.NewLoginService(loginUsecase, adminOperationLogUsecase)
	adminRepo := data.NewAdminRepo(dataData)
	adminUsecase := biz.NewAdminUsecase(adminRepo)
	roleRepo := data.NewRoleRepo(dataData)
	roleUsecase := biz.NewRoleUsecase(roleRepo)
	adminRoleRepo := data.NewAdminRoleRepo(dataData)
	adminRoleUsecase := biz.NewAdminRoleUsecase(adminRoleRepo)
	permissionRepo := data.NewPermissionRepo(dataData)
	permissionUsecase := biz.NewPermissionUsecase(permissionRepo)
	groupPermissionRepo := data.NewGroupPermissionRepo(dataData)
	groupPermissionUsecase := biz.NewGroupPermissionUsecase(groupPermissionRepo)
	adminService := service.NewAdminService(adminUsecase, roleUsecase, adminRoleUsecase, permissionUsecase, groupPermissionUsecase, adminOperationLogUsecase)
	grpcServer := server.NewGRPCServer(confServer, todoService, loginService, adminService)
	httpServer := server.NewHTTPServer(confServer, auth, adminOperationLogUsecase, todoService, loginService, adminService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
