// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"crow/internal/biz"
	"crow/internal/conf"
	"crow/internal/data"
	"crow/internal/server"
	"crow/internal/service"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger *slog.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	adminOperationLogRepo := data.NewAdminOperationLogRepo(dataData)
	adminOperationLogUsecase := biz.NewAdminOperationLogUsecase(adminOperationLogRepo)
	todoRepo := data.NewTodoRepo(dataData)
	todoUsecase := biz.NewTodoUsecase(todoRepo)
	todoService := service.NewTodoService(todoUsecase)
	loginRepo := data.NewLoginRepo(dataData)
	tokenGenerator := biz.NewLoginTokenGenerator(auth)
	loginUsecase := biz.NewLoginUsecase(loginRepo, tokenGenerator)
	loginService := service.NewLoginService(loginUsecase, adminOperationLogUsecase)
	adminRepo := data.NewAdminRepo(dataData)
	adminUsecase := biz.NewAdminUsecase(adminRepo)
	roleRepo := data.NewRoleRepo(dataData)
	roleUsecase := biz.NewRoleUsecase(roleRepo)
	adminRoleRepo := data.NewAdminRoleRepo(dataData)
	adminRoleUsecase := biz.NewAdminRoleUsecase(adminRoleRepo)
	permissionRepo := data.NewPermissionRepo(dataData)
	permissionUsecase := biz.NewPermissionUsecase(permissionRepo)
	groupPermissionRepo := data.NewGroupPermissionRepo(dataData)
	groupPermissionUsecase := biz.NewGroupPermissionUsecase(groupPermissionRepo)
	systemLogRepo := data.NewSystemLogRepo(dataData)
	systemLogUsecase := biz.NewSystemLogUsecase(systemLogRepo)
	adminService := service.NewAdminService(adminUsecase, roleUsecase, adminRoleUsecase, permissionUsecase, groupPermissionUsecase, adminOperationLogUsecase, systemLogUsecase)
	cpRepo := data.NewCpRepo(dataData)
	cpUsecase := biz.NewCpUsecase(cpRepo)
	cpService := service.NewCpService(cpUsecase)
	spRepo := data.NewSpRepo(dataData)
	spUsecase := biz.NewSpUsecase(spRepo)
	spService := service.NewSpService(spUsecase)
	cpSpRepo := data.NewCpSpRepo(dataData)
	cpSpUsecase := biz.NewCpSpUsecase(cpSpRepo)
	cpSpService := service.NewCpSpService(cpSpUsecase)
	vodRepo := data.NewVodRepo(dataData)
	vodUsecase := biz.NewVodUsecase(vodRepo)
	vodService := service.NewVodService(vodUsecase)
	httpServer := server.NewHTTPServer(confServer, auth, adminOperationLogUsecase, todoService, loginService, adminService, cpService, spService, cpSpService, vodService)
	app := newApp(logger, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
