// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: vod/v1/vod.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SortOrder     int32                  `protobuf:"varint,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        uint32                 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_vod_v1_vod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Category) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Category) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Category) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type CategorySet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategorySet) Reset() {
	*x = CategorySet{}
	mi := &file_vod_v1_vod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySet) ProtoMessage() {}

func (x *CategorySet) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySet.ProtoReflect.Descriptor instead.
func (*CategorySet) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{1}
}

func (x *CategorySet) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{2}
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCategoryRequest) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type Video struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId          int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	VideoCode           string                 `protobuf:"bytes,3,opt,name=video_code,json=videoCode,proto3" json:"video_code,omitempty"`
	Title               string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle            string                 `protobuf:"bytes,5,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	VideoType           uint32                 `protobuf:"varint,6,opt,name=video_type,json=videoType,proto3" json:"video_type,omitempty"`
	PosterVerticalUrl   string                 `protobuf:"bytes,7,opt,name=poster_vertical_url,json=posterVerticalUrl,proto3" json:"poster_vertical_url,omitempty"`
	PosterHorizontalUrl string                 `protobuf:"bytes,8,opt,name=poster_horizontal_url,json=posterHorizontalUrl,proto3" json:"poster_horizontal_url,omitempty"`
	ThumbnailUrl        string                 `protobuf:"bytes,9,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Description         string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Year                uint32                 `protobuf:"varint,11,opt,name=year,proto3" json:"year,omitempty"`
	Duration            uint32                 `protobuf:"varint,12,opt,name=duration,proto3" json:"duration,omitempty"`
	Status              uint32                 `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime          *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_vod_v1_vod_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{4}
}

func (x *Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Video) GetVideoCode() string {
	if x != nil {
		return x.VideoCode
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Video) GetVideoType() uint32 {
	if x != nil {
		return x.VideoType
	}
	return 0
}

func (x *Video) GetPosterVerticalUrl() string {
	if x != nil {
		return x.PosterVerticalUrl
	}
	return ""
}

func (x *Video) GetPosterHorizontalUrl() string {
	if x != nil {
		return x.PosterHorizontalUrl
	}
	return ""
}

func (x *Video) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Video) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Video) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Video) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Video) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Video) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Video) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type VideoSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoSet) Reset() {
	*x = VideoSet{}
	mi := &file_vod_v1_vod_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoSet) ProtoMessage() {}

func (x *VideoSet) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoSet.ProtoReflect.Descriptor instead.
func (*VideoSet) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{5}
}

func (x *VideoSet) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

type CreateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *Video                 `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoRequest) Reset() {
	*x = CreateVideoRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoRequest) ProtoMessage() {}

func (x *CreateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{6}
}

func (x *CreateVideoRequest) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosRequest) Reset() {
	*x = ListVideosRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosRequest) ProtoMessage() {}

func (x *ListVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosRequest.ProtoReflect.Descriptor instead.
func (*ListVideosRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{8}
}

func (x *ListVideosRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ListVideosRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type DeleteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoRequest) Reset() {
	*x = DeleteVideoRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoRequest) ProtoMessage() {}

func (x *DeleteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteVideoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Episode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	EpisodeNo     uint32                 `protobuf:"varint,3,opt,name=episode_no,json=episodeNo,proto3" json:"episode_no,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Duration      uint32                 `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Status        uint32                 `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Episode) Reset() {
	*x = Episode{}
	mi := &file_vod_v1_vod_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Episode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Episode) ProtoMessage() {}

func (x *Episode) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Episode.ProtoReflect.Descriptor instead.
func (*Episode) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{10}
}

func (x *Episode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Episode) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *Episode) GetEpisodeNo() uint32 {
	if x != nil {
		return x.EpisodeNo
	}
	return 0
}

func (x *Episode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Episode) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Episode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Episode) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Episode) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Episode) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type EpisodeSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Episodes      []*Episode             `protobuf:"bytes,1,rep,name=episodes,proto3" json:"episodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeSet) Reset() {
	*x = EpisodeSet{}
	mi := &file_vod_v1_vod_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeSet) ProtoMessage() {}

func (x *EpisodeSet) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeSet.ProtoReflect.Descriptor instead.
func (*EpisodeSet) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{11}
}

func (x *EpisodeSet) GetEpisodes() []*Episode {
	if x != nil {
		return x.Episodes
	}
	return nil
}

type CreateEpisodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Episode       *Episode               `protobuf:"bytes,1,opt,name=episode,proto3" json:"episode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEpisodeRequest) Reset() {
	*x = CreateEpisodeRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEpisodeRequest) ProtoMessage() {}

func (x *CreateEpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEpisodeRequest.ProtoReflect.Descriptor instead.
func (*CreateEpisodeRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{12}
}

func (x *CreateEpisodeRequest) GetEpisode() *Episode {
	if x != nil {
		return x.Episode
	}
	return nil
}

type ListEpisodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEpisodesRequest) Reset() {
	*x = ListEpisodesRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEpisodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEpisodesRequest) ProtoMessage() {}

func (x *ListEpisodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEpisodesRequest.ProtoReflect.Descriptor instead.
func (*ListEpisodesRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{13}
}

func (x *ListEpisodesRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

type DeleteEpisodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEpisodeRequest) Reset() {
	*x = DeleteEpisodeRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEpisodeRequest) ProtoMessage() {}

func (x *DeleteEpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEpisodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEpisodeRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteEpisodeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	EpisodeId     int64                  `protobuf:"varint,3,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	MediaId       string                 `protobuf:"bytes,4,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	MediaUrl      string                 `protobuf:"bytes,5,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	FileFormat    string                 `protobuf:"bytes,6,opt,name=file_format,json=fileFormat,proto3" json:"file_format,omitempty"`
	Bitrate       uint32                 `protobuf:"varint,7,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Resolution    string                 `protobuf:"bytes,8,opt,name=resolution,proto3" json:"resolution,omitempty"`
	FileSize      uint64                 `protobuf:"varint,9,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Duration      uint32                 `protobuf:"varint,10,opt,name=duration,proto3" json:"duration,omitempty"`
	Status        uint32                 `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_vod_v1_vod_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{15}
}

func (x *Media) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *Media) GetEpisodeId() int64 {
	if x != nil {
		return x.EpisodeId
	}
	return 0
}

func (x *Media) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Media) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *Media) GetFileFormat() string {
	if x != nil {
		return x.FileFormat
	}
	return ""
}

func (x *Media) GetBitrate() uint32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *Media) GetResolution() string {
	if x != nil {
		return x.Resolution
	}
	return ""
}

func (x *Media) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Media) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Media) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Media) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Media) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type MediaSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*Media               `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaSet) Reset() {
	*x = MediaSet{}
	mi := &file_vod_v1_vod_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSet) ProtoMessage() {}

func (x *MediaSet) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSet.ProtoReflect.Descriptor instead.
func (*MediaSet) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{16}
}

func (x *MediaSet) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type CreateMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMediaRequest) Reset() {
	*x = CreateMediaRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaRequest) ProtoMessage() {}

func (x *CreateMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaRequest.ProtoReflect.Descriptor instead.
func (*CreateMediaRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{17}
}

func (x *CreateMediaRequest) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type ListMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId     int64                  `protobuf:"varint,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaRequest) Reset() {
	*x = ListMediaRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaRequest) ProtoMessage() {}

func (x *ListMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaRequest.ProtoReflect.Descriptor instead.
func (*ListMediaRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{18}
}

func (x *ListMediaRequest) GetEpisodeId() int64 {
	if x != nil {
		return x.EpisodeId
	}
	return 0
}

type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_vod_v1_vod_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_vod_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_vod_v1_vod_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteMediaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_vod_v1_vod_proto protoreflect.FileDescriptor

const file_vod_v1_vod_proto_rawDesc = "" +
	"\n" +
	"\x10vod/v1/vod.proto\x12\x06vod.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\x05 \x01(\rR\x06status\x12;\n" +
	"\vcreate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"?\n" +
	"\vCategorySet\x120\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x10.vod.v1.CategoryR\n" +
	"categories\"\x17\n" +
	"\x15ListCategoriesRequest\"J\n" +
	"\x15CreateCategoryRequest\x121\n" +
	"\bcategory\x18\x01 \x01(\v2\x10.vod.v1.CategoryB\x03\xe0A\x02R\bcategory\"\x95\x04\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"video_code\x18\x03 \x01(\tR\tvideoCode\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x05 \x01(\tR\bsubtitle\x12\x1d\n" +
	"\n" +
	"video_type\x18\x06 \x01(\rR\tvideoType\x12.\n" +
	"\x13poster_vertical_url\x18\a \x01(\tR\x11posterVerticalUrl\x122\n" +
	"\x15poster_horizontal_url\x18\b \x01(\tR\x13posterHorizontalUrl\x12#\n" +
	"\rthumbnail_url\x18\t \x01(\tR\fthumbnailUrl\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x12\n" +
	"\x04year\x18\v \x01(\rR\x04year\x12\x1a\n" +
	"\bduration\x18\f \x01(\rR\bduration\x12\x16\n" +
	"\x06status\x18\r \x01(\rR\x06status\x12;\n" +
	"\vcreate_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"1\n" +
	"\bVideoSet\x12%\n" +
	"\x06videos\x18\x01 \x03(\v2\r.vod.v1.VideoR\x06videos\">\n" +
	"\x12CreateVideoRequest\x12(\n" +
	"\x05video\x18\x01 \x01(\v2\r.vod.v1.VideoB\x03\xe0A\x02R\x05video\"&\n" +
	"\x0fGetVideoRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"N\n" +
	"\x11ListVideosRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\")\n" +
	"\x12DeleteVideoRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\xb9\x02\n" +
	"\aEpisode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x1d\n" +
	"\n" +
	"episode_no\x18\x03 \x01(\rR\tepisodeNo\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\rR\bduration\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\a \x01(\rR\x06status\x12;\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"9\n" +
	"\n" +
	"EpisodeSet\x12+\n" +
	"\bepisodes\x18\x01 \x03(\v2\x0f.vod.v1.EpisodeR\bepisodes\"F\n" +
	"\x14CreateEpisodeRequest\x12.\n" +
	"\aepisode\x18\x01 \x01(\v2\x0f.vod.v1.EpisodeB\x03\xe0A\x02R\aepisode\"5\n" +
	"\x13ListEpisodesRequest\x12\x1e\n" +
	"\bvideo_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\avideoId\"+\n" +
	"\x14DeleteEpisodeRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id\"\xaf\x03\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x03 \x01(\x03R\tepisodeId\x12\x19\n" +
	"\bmedia_id\x18\x04 \x01(\tR\amediaId\x12\x1b\n" +
	"\tmedia_url\x18\x05 \x01(\tR\bmediaUrl\x12\x1f\n" +
	"\vfile_format\x18\x06 \x01(\tR\n" +
	"fileFormat\x12\x18\n" +
	"\abitrate\x18\a \x01(\rR\abitrate\x12\x1e\n" +
	"\n" +
	"resolution\x18\b \x01(\tR\n" +
	"resolution\x12\x1b\n" +
	"\tfile_size\x18\t \x01(\x04R\bfileSize\x12\x1a\n" +
	"\bduration\x18\n" +
	" \x01(\rR\bduration\x12\x16\n" +
	"\x06status\x18\v \x01(\rR\x06status\x12;\n" +
	"\vcreate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"/\n" +
	"\bMediaSet\x12#\n" +
	"\x05media\x18\x01 \x03(\v2\r.vod.v1.MediaR\x05media\">\n" +
	"\x12CreateMediaRequest\x12(\n" +
	"\x05media\x18\x01 \x01(\v2\r.vod.v1.MediaB\x03\xe0A\x02R\x05media\"6\n" +
	"\x10ListMediaRequest\x12\"\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\x03B\x03\xe0A\x02R\tepisodeId\")\n" +
	"\x12DeleteMediaRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03B\x03\xe0A\x02R\x02id2\xd7\b\n" +
	"\n" +
	"VodService\x12b\n" +
	"\x0eListCategories\x12\x1d.vod.v1.ListCategoriesRequest\x1a\x13.vod.v1.CategorySet\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/video-categories\x12p\n" +
	"\x0eCreateCategory\x12\x1d.vod.v1.CreateCategoryRequest\x1a\x10.vod.v1.Category\"-\x82\xd3\xe4\x93\x02':\bcategory\"\x1b/v1/video-categories/create\x12Z\n" +
	"\vCreateVideo\x12\x1a.vod.v1.CreateVideoRequest\x1a\r.vod.v1.Video\" \x82\xd3\xe4\x93\x02\x1a:\x05video\"\x11/v1/videos/create\x12K\n" +
	"\bGetVideo\x12\x17.vod.v1.GetVideoRequest\x1a\r.vod.v1.Video\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/videos/{id}\x12M\n" +
	"\n" +
	"ListVideos\x12\x19.vod.v1.ListVideosRequest\x1a\x10.vod.v1.VideoSet\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/videos\x12Z\n" +
	"\vDeleteVideo\x12\x1a.vod.v1.DeleteVideoRequest\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/videos/{id}\x12d\n" +
	"\rCreateEpisode\x12\x1c.vod.v1.CreateEpisodeRequest\x1a\x0f.vod.v1.Episode\"$\x82\xd3\xe4\x93\x02\x1e:\aepisode\"\x13/v1/episodes/create\x12U\n" +
	"\fListEpisodes\x12\x1b.vod.v1.ListEpisodesRequest\x1a\x12.vod.v1.EpisodeSet\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/episodes\x12`\n" +
	"\rDeleteEpisode\x12\x1c.vod.v1.DeleteEpisodeRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/episodes/{id}\x12Y\n" +
	"\vCreateMedia\x12\x1a.vod.v1.CreateMediaRequest\x1a\r.vod.v1.Media\"\x1f\x82\xd3\xe4\x93\x02\x19:\x05media\"\x10/v1/media/create\x12J\n" +
	"\tListMedia\x12\x18.vod.v1.ListMediaRequest\x1a\x10.vod.v1.MediaSet\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/media\x12Y\n" +
	"\vDeleteMedia\x12\x1a.vod.v1.DeleteMediaRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/media/{id}B\x14Z\x12crow/api/vod/v1;v1b\x06proto3"

var (
	file_vod_v1_vod_proto_rawDescOnce sync.Once
	file_vod_v1_vod_proto_rawDescData []byte
)

func file_vod_v1_vod_proto_rawDescGZIP() []byte {
	file_vod_v1_vod_proto_rawDescOnce.Do(func() {
		file_vod_v1_vod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vod_v1_vod_proto_rawDesc), len(file_vod_v1_vod_proto_rawDesc)))
	})
	return file_vod_v1_vod_proto_rawDescData
}

var file_vod_v1_vod_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_vod_v1_vod_proto_goTypes = []any{
	(*Category)(nil),              // 0: vod.v1.Category
	(*CategorySet)(nil),           // 1: vod.v1.CategorySet
	(*ListCategoriesRequest)(nil), // 2: vod.v1.ListCategoriesRequest
	(*CreateCategoryRequest)(nil), // 3: vod.v1.CreateCategoryRequest
	(*Video)(nil),                 // 4: vod.v1.Video
	(*VideoSet)(nil),              // 5: vod.v1.VideoSet
	(*CreateVideoRequest)(nil),    // 6: vod.v1.CreateVideoRequest
	(*GetVideoRequest)(nil),       // 7: vod.v1.GetVideoRequest
	(*ListVideosRequest)(nil),     // 8: vod.v1.ListVideosRequest
	(*DeleteVideoRequest)(nil),    // 9: vod.v1.DeleteVideoRequest
	(*Episode)(nil),               // 10: vod.v1.Episode
	(*EpisodeSet)(nil),            // 11: vod.v1.EpisodeSet
	(*CreateEpisodeRequest)(nil),  // 12: vod.v1.CreateEpisodeRequest
	(*ListEpisodesRequest)(nil),   // 13: vod.v1.ListEpisodesRequest
	(*DeleteEpisodeRequest)(nil),  // 14: vod.v1.DeleteEpisodeRequest
	(*Media)(nil),                 // 15: vod.v1.Media
	(*MediaSet)(nil),              // 16: vod.v1.MediaSet
	(*CreateMediaRequest)(nil),    // 17: vod.v1.CreateMediaRequest
	(*ListMediaRequest)(nil),      // 18: vod.v1.ListMediaRequest
	(*DeleteMediaRequest)(nil),    // 19: vod.v1.DeleteMediaRequest
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 21: google.protobuf.Empty
}
var file_vod_v1_vod_proto_depIdxs = []int32{
	20, // 0: vod.v1.Category.create_time:type_name -> google.protobuf.Timestamp
	20, // 1: vod.v1.Category.update_time:type_name -> google.protobuf.Timestamp
	0,  // 2: vod.v1.CategorySet.categories:type_name -> vod.v1.Category
	0,  // 3: vod.v1.CreateCategoryRequest.category:type_name -> vod.v1.Category
	20, // 4: vod.v1.Video.create_time:type_name -> google.protobuf.Timestamp
	20, // 5: vod.v1.Video.update_time:type_name -> google.protobuf.Timestamp
	4,  // 6: vod.v1.VideoSet.videos:type_name -> vod.v1.Video
	4,  // 7: vod.v1.CreateVideoRequest.video:type_name -> vod.v1.Video
	20, // 8: vod.v1.Episode.create_time:type_name -> google.protobuf.Timestamp
	20, // 9: vod.v1.Episode.update_time:type_name -> google.protobuf.Timestamp
	10, // 10: vod.v1.EpisodeSet.episodes:type_name -> vod.v1.Episode
	10, // 11: vod.v1.CreateEpisodeRequest.episode:type_name -> vod.v1.Episode
	20, // 12: vod.v1.Media.create_time:type_name -> google.protobuf.Timestamp
	20, // 13: vod.v1.Media.update_time:type_name -> google.protobuf.Timestamp
	15, // 14: vod.v1.MediaSet.media:type_name -> vod.v1.Media
	15, // 15: vod.v1.CreateMediaRequest.media:type_name -> vod.v1.Media
	2,  // 16: vod.v1.VodService.ListCategories:input_type -> vod.v1.ListCategoriesRequest
	3,  // 17: vod.v1.VodService.CreateCategory:input_type -> vod.v1.CreateCategoryRequest
	6,  // 18: vod.v1.VodService.CreateVideo:input_type -> vod.v1.CreateVideoRequest
	7,  // 19: vod.v1.VodService.GetVideo:input_type -> vod.v1.GetVideoRequest
	8,  // 20: vod.v1.VodService.ListVideos:input_type -> vod.v1.ListVideosRequest
	9,  // 21: vod.v1.VodService.DeleteVideo:input_type -> vod.v1.DeleteVideoRequest
	12, // 22: vod.v1.VodService.CreateEpisode:input_type -> vod.v1.CreateEpisodeRequest
	13, // 23: vod.v1.VodService.ListEpisodes:input_type -> vod.v1.ListEpisodesRequest
	14, // 24: vod.v1.VodService.DeleteEpisode:input_type -> vod.v1.DeleteEpisodeRequest
	17, // 25: vod.v1.VodService.CreateMedia:input_type -> vod.v1.CreateMediaRequest
	18, // 26: vod.v1.VodService.ListMedia:input_type -> vod.v1.ListMediaRequest
	19, // 27: vod.v1.VodService.DeleteMedia:input_type -> vod.v1.DeleteMediaRequest
	1,  // 28: vod.v1.VodService.ListCategories:output_type -> vod.v1.CategorySet
	0,  // 29: vod.v1.VodService.CreateCategory:output_type -> vod.v1.Category
	4,  // 30: vod.v1.VodService.CreateVideo:output_type -> vod.v1.Video
	4,  // 31: vod.v1.VodService.GetVideo:output_type -> vod.v1.Video
	5,  // 32: vod.v1.VodService.ListVideos:output_type -> vod.v1.VideoSet
	21, // 33: vod.v1.VodService.DeleteVideo:output_type -> google.protobuf.Empty
	10, // 34: vod.v1.VodService.CreateEpisode:output_type -> vod.v1.Episode
	11, // 35: vod.v1.VodService.ListEpisodes:output_type -> vod.v1.EpisodeSet
	21, // 36: vod.v1.VodService.DeleteEpisode:output_type -> google.protobuf.Empty
	15, // 37: vod.v1.VodService.CreateMedia:output_type -> vod.v1.Media
	16, // 38: vod.v1.VodService.ListMedia:output_type -> vod.v1.MediaSet
	21, // 39: vod.v1.VodService.DeleteMedia:output_type -> google.protobuf.Empty
	28, // [28:40] is the sub-list for method output_type
	16, // [16:28] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_vod_v1_vod_proto_init() }
func file_vod_v1_vod_proto_init() {
	if File_vod_v1_vod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vod_v1_vod_proto_rawDesc), len(file_vod_v1_vod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vod_v1_vod_proto_goTypes,
		DependencyIndexes: file_vod_v1_vod_proto_depIdxs,
		MessageInfos:      file_vod_v1_vod_proto_msgTypes,
	}.Build()
	File_vod_v1_vod_proto = out.File
	file_vod_v1_vod_proto_goTypes = nil
	file_vod_v1_vod_proto_depIdxs = nil
}
