// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: vod/v1/vod.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationVodServiceCreateCategory = "/vod.v1.VodService/CreateCategory"
const OperationVodServiceCreateEpisode = "/vod.v1.VodService/CreateEpisode"
const OperationVodServiceCreateMedia = "/vod.v1.VodService/CreateMedia"
const OperationVodServiceCreateVideo = "/vod.v1.VodService/CreateVideo"
const OperationVodServiceDeleteEpisode = "/vod.v1.VodService/DeleteEpisode"
const OperationVodServiceDeleteMedia = "/vod.v1.VodService/DeleteMedia"
const OperationVodServiceDeleteVideo = "/vod.v1.VodService/DeleteVideo"
const OperationVodServiceGetVideo = "/vod.v1.VodService/GetVideo"
const OperationVodServiceListCategories = "/vod.v1.VodService/ListCategories"
const OperationVodServiceListEpisodes = "/vod.v1.VodService/ListEpisodes"
const OperationVodServiceListMedia = "/vod.v1.VodService/ListMedia"
const OperationVodServiceListVideos = "/vod.v1.VodService/ListVideos"

type VodServiceHTTPServer interface {
	CreateCategory(context.Context, *CreateCategoryRequest) (*Category, error)
	CreateEpisode(context.Context, *CreateEpisodeRequest) (*Episode, error)
	CreateMedia(context.Context, *CreateMediaRequest) (*Media, error)
	CreateVideo(context.Context, *CreateVideoRequest) (*Video, error)
	DeleteEpisode(context.Context, *DeleteEpisodeRequest) (*emptypb.Empty, error)
	DeleteMedia(context.Context, *DeleteMediaRequest) (*emptypb.Empty, error)
	DeleteVideo(context.Context, *DeleteVideoRequest) (*emptypb.Empty, error)
	GetVideo(context.Context, *GetVideoRequest) (*Video, error)
	ListCategories(context.Context, *ListCategoriesRequest) (*CategorySet, error)
	ListEpisodes(context.Context, *ListEpisodesRequest) (*EpisodeSet, error)
	ListMedia(context.Context, *ListMediaRequest) (*MediaSet, error)
	ListVideos(context.Context, *ListVideosRequest) (*VideoSet, error)
}

func RegisterVodServiceHTTPServer(s *http.Server, srv VodServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/video-categories", _VodService_ListCategories0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/video-categories/create", _VodService_CreateCategory0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/videos/create", _VodService_CreateVideo0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/videos/{id}", _VodService_GetVideo0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/videos", _VodService_ListVideos0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/videos/{id}", _VodService_DeleteVideo0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/episodes/create", _VodService_CreateEpisode0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/episodes", _VodService_ListEpisodes0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/episodes/{id}", _VodService_DeleteEpisode0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/media/create", _VodService_CreateMedia0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/media", _VodService_ListMedia0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/media/{id}", _VodService_DeleteMedia0_HTTP_Handler(srv))
}

func _VodService_ListCategories0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCategoriesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceListCategories)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCategories(ctx, req.(*ListCategoriesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CategorySet)
		return ctx.Result(200, reply)
	}
}

func _VodService_CreateCategory0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCategoryRequest
		if err := ctx.Bind(&in.Category); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceCreateCategory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCategory(ctx, req.(*CreateCategoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Category)
		return ctx.Result(200, reply)
	}
}

func _VodService_CreateVideo0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateVideoRequest
		if err := ctx.Bind(&in.Video); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceCreateVideo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateVideo(ctx, req.(*CreateVideoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Video)
		return ctx.Result(200, reply)
	}
}

func _VodService_GetVideo0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetVideoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceGetVideo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetVideo(ctx, req.(*GetVideoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Video)
		return ctx.Result(200, reply)
	}
}

func _VodService_ListVideos0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListVideosRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceListVideos)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListVideos(ctx, req.(*ListVideosRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*VideoSet)
		return ctx.Result(200, reply)
	}
}

func _VodService_DeleteVideo0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteVideoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceDeleteVideo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteVideo(ctx, req.(*DeleteVideoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _VodService_CreateEpisode0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateEpisodeRequest
		if err := ctx.Bind(&in.Episode); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceCreateEpisode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateEpisode(ctx, req.(*CreateEpisodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Episode)
		return ctx.Result(200, reply)
	}
}

func _VodService_ListEpisodes0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListEpisodesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceListEpisodes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListEpisodes(ctx, req.(*ListEpisodesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EpisodeSet)
		return ctx.Result(200, reply)
	}
}

func _VodService_DeleteEpisode0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteEpisodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceDeleteEpisode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteEpisode(ctx, req.(*DeleteEpisodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _VodService_CreateMedia0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateMediaRequest
		if err := ctx.Bind(&in.Media); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceCreateMedia)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateMedia(ctx, req.(*CreateMediaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Media)
		return ctx.Result(200, reply)
	}
}

func _VodService_ListMedia0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMediaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceListMedia)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMedia(ctx, req.(*ListMediaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MediaSet)
		return ctx.Result(200, reply)
	}
}

func _VodService_DeleteMedia0_HTTP_Handler(srv VodServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteMediaRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationVodServiceDeleteMedia)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteMedia(ctx, req.(*DeleteMediaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type VodServiceHTTPClient interface {
	CreateCategory(ctx context.Context, req *CreateCategoryRequest, opts ...http.CallOption) (rsp *Category, err error)
	CreateEpisode(ctx context.Context, req *CreateEpisodeRequest, opts ...http.CallOption) (rsp *Episode, err error)
	CreateMedia(ctx context.Context, req *CreateMediaRequest, opts ...http.CallOption) (rsp *Media, err error)
	CreateVideo(ctx context.Context, req *CreateVideoRequest, opts ...http.CallOption) (rsp *Video, err error)
	DeleteEpisode(ctx context.Context, req *DeleteEpisodeRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteMedia(ctx context.Context, req *DeleteMediaRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	DeleteVideo(ctx context.Context, req *DeleteVideoRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	GetVideo(ctx context.Context, req *GetVideoRequest, opts ...http.CallOption) (rsp *Video, err error)
	ListCategories(ctx context.Context, req *ListCategoriesRequest, opts ...http.CallOption) (rsp *CategorySet, err error)
	ListEpisodes(ctx context.Context, req *ListEpisodesRequest, opts ...http.CallOption) (rsp *EpisodeSet, err error)
	ListMedia(ctx context.Context, req *ListMediaRequest, opts ...http.CallOption) (rsp *MediaSet, err error)
	ListVideos(ctx context.Context, req *ListVideosRequest, opts ...http.CallOption) (rsp *VideoSet, err error)
}

type VodServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewVodServiceHTTPClient(client *http.Client) VodServiceHTTPClient {
	return &VodServiceHTTPClientImpl{client}
}

func (c *VodServiceHTTPClientImpl) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...http.CallOption) (*Category, error) {
	var out Category
	pattern := "/v1/video-categories/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("category"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationVodServiceCreateCategory),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Category, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VodServiceHTTPClientImpl) CreateEpisode(ctx context.Context, in *CreateEpisodeRequest, opts ...http.CallOption) (*Episode, error) {
	var out Episode
	pattern := "/v1/episodes/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("episode"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationVodServiceCreateEpisode),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Episode, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VodServiceHTTPClientImpl) CreateMedia(ctx context.Context, in *CreateMediaRequest, opts ...http.CallOption) (*Media, error) {
	var out Media
	pattern := "/v1/media/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("media"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationVodServiceCreateMedia),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Media, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VodServiceHTTPClientImpl) CreateVideo(ctx context.Context, in *CreateVideoRequest, opts ...http.CallOption) (*Video, error) {
	var out Video
	pattern := "/v1/videos/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("video"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationVodServiceCreateVideo),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Video, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VodServiceHTTPClientImpl) DeleteEpisode(ctx context.Context, in *DeleteEpisodeRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/episodes/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationVodServiceDeleteEpisode),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VodServiceHTTPClientImpl) DeleteMedia(ctx context.Context, in *DeleteMediaRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/media/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationVodServiceDeleteMedia),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VodServiceHTTPClientImpl) DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/videos/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationVodServiceDeleteVideo),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VodServiceHTTPClientImpl) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...http.CallOption) (*Video, error) {
	var out Video
	pattern := "/v1/videos/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationVodServiceGetVideo),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VodServiceHTTPClientImpl) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...http.CallOption) (*CategorySet, error) {
	var out CategorySet
	pattern := "/v1/video-categories"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationVodServiceListCategories),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VodServiceHTTPClientImpl) ListEpisodes(ctx context.Context, in *ListEpisodesRequest, opts ...http.CallOption) (*EpisodeSet, error) {
	var out EpisodeSet
	pattern := "/v1/episodes"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationVodServiceListEpisodes),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VodServiceHTTPClientImpl) ListMedia(ctx context.Context, in *ListMediaRequest, opts ...http.CallOption) (*MediaSet, error) {
	var out MediaSet
	pattern := "/v1/media"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationVodServiceListMedia),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *VodServiceHTTPClientImpl) ListVideos(ctx context.Context, in *ListVideosRequest, opts ...http.CallOption) (*VideoSet, error) {
	var out VideoSet
	pattern := "/v1/videos"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationVodServiceListVideos),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
